app/bank.py

変数初期化エラーの修正
```
Jun 01 09:39:44 obi python3[15284]: device info error!
Jun 01 09:39:44 obi python3[15284]: Traceback (most recent call last):
Jun 01 09:39:44 obi python3[15284]:   File "/opt/ota/client/app/ota_client_service.py", line 275, in <module>
Jun 01 09:39:44 obi python3[15284]:     otaboot = OtaBoot()
Jun 01 09:39:44 obi python3[15284]:   File "/opt/ota/client/app/ota_boot.py", line 36, in _init_
Jun 01 09:39:44 obi python3[15284]:     self._grub_ctl = GrubCtl(
Jun 01 09:39:44 obi python3[15284]:   File "/opt/ota/client/app/grub_control.py", line 27, in _init_
Jun 01 09:39:44 obi python3[15284]:     self._bank_info = BankInfo(bank_info_file=bank_info_file, fstab_file=fstab_file)
Jun 01 09:39:44 obi python3[15284]:   File "/opt/ota/client/app/bank.py", line 29, in _init_
Jun 01 …
```

bugfix: initialize error.

---

app/ota_client.py

_copytree_complete()でdirectoryのownerがコピーできていないケースが発生。
directoryの作成にos.makedirs()を使用した場合、複数改装ある場合に最終改装以外のownerが変更できていない。
すべての階層でownerを変更するため_copydirs_complete()を作成し、os.makedirs()の代わりに使用するように変更。

_copytree_complete()でdirectoryのownerがコピーできていない問題の修正

---

app/bank.py
app/grub_control.py
tests/test_grub_control.py

```
GRUB_TIMEOUT_STYLE=menu
GRUB_TIMEOUT=10
GRUB_DISTRIBUTOR=`lsb_release -i -s 2> /dev/null || echo Debian`
```
が
```
GRUB_TIMEOUT_STYLE=menuGRUB_TIMEOUT=10GRUB_DISTRIBUTOR=`lsb_release -i -s 2> /dev/null || echo Debian`
```
に連結されてしまう問題を修正

Fix grub configuration

---

.github/workflows/test.yml

Previous **test CI** workflow will always failed due to the fail of the step **Add coverage report to PR comment** when the PR creator is not listed as maintainer of the repo, or the PR is not from the branch within the main repo.
To solve the problem, this step can be mark as optional, A.K.A not failing the whole job even this step failed.

[T4PUB-331] Mark step "Add coverage report to PR comment" as optional

---

app/ota_client.py

Deepcopy should be used when intend to assign one dict's contents to another variable.

[T4PUB-363] Fix incorrect way of assignment for dict type

---

app/ota_client.py

Reboot after OTA applied is being done via OtaClientService currently,
It is also better to execute reboot by OtaClientService.

Remove unused parameter "reboot" in OtaClient._update

---

app/grub_control.py
app/ota_client.py

Current ota client cannot update kernel image(vmlinuz and initrd).
_boot_vmlinuz and _boot_initrd were set by sub-process, so global_var_dict is used to pass those value.
https://tier4.atlassian.net/browse/T4PUB-428
https://tier4.atlassian.net/browse/T4PB-9255

[T4PUB-428] [T4PB-9255] fix kernel updating

---

app/ota_client.py

In previous implementation, **_process_regular_files** use **error_callback** to terminate the pool if any subprocess fails.
It may cause the main process hanging in some cases.
This bug fix use a synchronized **manager.event** to notify the main process to terminate the pool.
Along with this change, a **manager.list** object is used to act as await counter, to ensure that all subprocess finished their job, instead of using **pool.join**, since we need to actively polling that **manager.event**.
TODO: a timeout counter can be added to prevent hanging.

[BugFix] ota-client.py: fix potential bug in _process_regular_files

---

.gitignore
app2/ota_client.py
docker-compose.yml
docker/client/Dockerfile
docker/server/Dockerfile

Some improvement and code cleanup for e2e tests dockerfiles and docker-compose file.
* dockerfiles: combine related steps into one RUN to reduce unnecessary intermediate layers
* docker-compose file: 
previously we mount the local code base as rw into the client container, that is not a good idea as
the container may effect the host file system when we are running pytest. now we mount the local
code base as ro, and copy the new code base to the working dir.

improvement for dockerfiles of e2e tests

---

README.md
app/ota_client.py
app/otaclient_v2_pb2.py
proto/otaclient_v2.proto

- use sha256.update not to consume much memory when calculating file digest. (see T4PB-12875)
- fix proto type from 32bit to 64bit, since the total file size is overflowing.
https://tier4.atlassian.net/browse/T4PB-12875
https://tier4.atlassian.net/browse/T4PB-12804
https://tier4.atlassian.net/browse/T4PB-12806 (this might be caused by memory consumption)

[T4PB-12875] [T4PB-12804] proto type, use update in sha256_file and add sleep when download failure

---

app/ota_client.py
app/requirements.txt
tests/test_ota_client-update.py

This PR adds
- stream=True as `requests.get` parameter.
- retry timeout with exponential backoff.
- add exception handler for `response.iter_content`, since stream=True is added.
https://tier4.atlassian.net/browse/T4PB-12875
https://tier4.atlassian.net/browse/T4PB-12924
https://tier4.atlassian.net/browse/T4PB-12887

[T4PB-12875] [T4PB-12924], [T4PB-12887] use stream

---

app/copy_tree.py
tests/test_copy_tree.py

when /opt/autoware/maps is symlink(or file in this case) and /mnt/standby/opt/autoware/maps is directory, persistent process failed.
This PR fixes this issue.
And also this PR support this scenario: if src is directory and dst is file or symlink, 
https://tier4.atlassian.net/browse/T4PB-13101
OTA tested on the actual system.

[T4PB-13101] support persistent if src file -> dst dir, src dir -> dst file

---

app/ota_client.py
app/ota_client_stub.py
app/ota_error.py
app/ota_status.py
tests/test_ota_client-update.py
tests/test_ota_client_service.py

OTA client has a bug that OTA client doesn't clear failure_type and failure_reason even new update request is received.
Also, this RP changes to wait for update initialization.
When the user requests `update`, and polls `status`, the `status` may return the status which is before the update request.
This is difficult for the user to use `update` and after `status` call.
https://tier4.atlassian.net/browse/T4PB-13100

[T4PB-13100] clear failure. wait update inittialized.

---

app/grub_control.py
app/ota_partition.py

When the system is force reset without poweroff or reboot command during the update sequence, the system will not boot.
The problems we faced:
- grub.cfg is corrupted.
- /boot/ota-partition isn't switched
- after rebooting(with force reset), grub loader uses unintended grub.cfg? and booted with unintended partition.
This PR fixes this issue.
https://tier4.atlassian.net/browse/T4PB-13258

[T4PB-13258] adding sync operation

---

app/ota_client.py
tests/test_ota_client-status.py

The previous implementation of OtaClientStatistics collecting logic may cause the statistics not being updated properly or missing updates when grpc *status* API being called with very short interval.
This PR fixes this problem by refactoring the statistics collecting logic, and improves the performance. The format of OtaStatistics is not changed.
Unit tests are passed for this PR.

Refactor of OtaClientStatistics collecting logic

---

app/configs.py
app/extlinux_control.py
app/grub_control.py
app/grub_ota_partition.py
app/ota_client.py

Supporting nvme boot with ota-client, along with improvement over extlinux_control module and configs module
1. ota-client now supports 2 kinds of boot-from-nvme-storage mechanism:
1.1: rootfs on nvme storage(tested, working as expected)
1.2: native boot from nvme storage(not tested, but extlinux_control module should support it)
2. ota-client can automatically detect the present of rootfs on external storage, and also backward support boot with internal storage if the ROSCUBE-X runs on internal storage
3. refactor to the configs module, use built-in dataclasses to compose Config class
4. other minor changes and cleanup
The ota-client support 2 kinds of boot-from-nvme-storage mechanism as follow: 
1. When detects the present of external nvme storage, ota-client will first update the …

[T4PUB-663] Support nvme boot with ota-client on ROSCUBE-X

---

app/ota_client.py

This PR fixes the issue that ota-client downloads all files from the server w/o copying from active bank if file size attribute is not set.

add condition where filesize is None

---

app/aws_gglog/boto3_session.py
app/aws_gglog/greengrass_config.py
app/aws_gglog/logger.py
tests/aws_gglog/test_boto3_session.py
tests/aws_gglog/test_greengrass_config.py
tests/aws_gglog/test_logger.py

This PR fixes two things:
1. `_set_cloudwatch_log_handler` is done in the thread and wait until getting a session in case of HTTP proxy is used and HTTP proxy server is not launched.
2. modify parameter to pass the certification config w/o greengrass config to support a non-greengrass environment.
https://tier4.atlassian.net/browse/T4PUB-705

add support sub-ecu logger

---

ota_proxy/__init__.py
ota_proxy/config.py
ota_proxy/db.py
ota_proxy/ota_cache.py
ota_proxy/server_app.py

This PR implements a cache-enabled standalone http proxy server dedicated for streaming OTA updates to subECUs.
This ota_proxy server runs as an independent proxy server. It will cache the OTA files request by URL, and stream the files to the subECUs.
1. https is not supported between mainECU and subECUs as we enable cached.
2. https is supported when mainECU fetch files from the internet.
3. currently the server will stop caching if the disk which cache_dir on usage reach 70%.

Implement ota_http_proxy server

---

aws-iot-log-server/app/aws_iot_logger.py
aws-iot-log-server/app/custom_http_handler.py

This PR makes it possible to send logs even if the order of launching the http proxy server and ota-client is different.
The previous implementation dropped ota-client log at the beginning.
This PR is confirmed by OTA image with https://github.com/tier4/autoware_ecu_system_setup/pull/154

fix http log robustness

---

app/configs.py
app/ecu_info.py
app/main.py
app/ota_client.py
app/ota_client_stub.py
app/proxy_info.py
app/requirements.txt
ota_proxy/config.py
ota_proxy/db.py
ota_proxy/ota_cache.py
ota_proxy/server_app.py
tests/test_ota_client-update.py

This PR integrates the ota_proxy server into the ota_client.
1. introduce proxy_info.yaml, this configuration file configures proxy settings for ota_client, including ota_proxy and generic proxy
2. integrate ota_proxy into ota_client, ota_proxy server will be launched on ota_update only, and being closed after ota update finished
3. refactor `ota_client._downloader` into `Downloader`
a. use `session(connection pool)` to handle all requests
b. use `Retry` from urllib3 with `requests.HTTPAdapter` to implement better retry mechanism
https://tier4.atlassian.net/browse/T4PUB-644
https://tier4.atlassian.net/browse/T4PUB-644
https://tier4.atlassian.net/browse/T4PB-11208

Integrate ota_proxy into ota_client

---

ota_proxy/ota_cache.py

ota_proxy module receives quoted requests from client, but previously it sent the request as it to the remote, without quoting it back, which causes the issue.
This PR fixes the issue by parsing and quoting the received request before sending it to the remote.

ota_proxy: quote the raw_url again before request it

---

app/ota_client.py
app/ota_client_stub.py

This PR removes sub ecu update completion timeout.
Since we can't define the timeout value.
And LOCAL_OTA_UPDATE_TIMEOUT is also removed. See T4PUB-790.
https://tier4.atlassian.net/browse/T4PUB-789
https://tier4.atlassian.net/browse/T4PUB-790

remove subecu timeout

---

docker-compose.yml
tests/conftest.py
tests/test_ota_client_service.py

This PR fix some issues in the test files to let pytest finish the test properly.
1. add ota_proxy module to the test environment
2. conftest.py: minor fix on path adding
3. test_ota_client_service.py: mock `_ensure_subecu_status`

Fix test files

---

app/ota_client.py
tests/requirements.txt

Previously, I introduce `multiprocessing.imap_unordered` to accelerate the `RegularInf` parsing.
But after small scale tests with `memory profiling` and `timeit`, I found that comparing to the time it saves(around 10seconds), it consume 200MB~ extra memory, which is not so efficient.
This PR dips the use of `multiprocessing.imap_unordered`, and also reduce some memory footprint for `RegularInf` class.
For one mainecu and one subecu environment, the memory usage on the mainecu drops from `867M~` to `664M~`.

Fix large memory use caused by the use of multiprocessing.imap_unordered.

---

app/ota_client_stub.py
ota_proxy/ota_cache.py

Ota-update is much slower(5x times) with ota-proxy than without ota-proxy.
According to the investigation, the bottleneck is the cache entry committing into sqlite db in ota-proxy's cache implemenation.
This PR provide a first-aid fix to avoid this issue by disable the ota-proxy's cache mechanims, make ota-proxy a pure proxy server.
1. cache mechanism is disabled for ota-proxy.
2. fix an issue of ota-cache module initializing.

Temporary fix for ota-proxy performance.

---

app/extlinux_control.py

Current implementation copies {standby nvme}/boot to {standby emmc}/boot and {standby emmc}/boot/boot is created as a result.
This PR added -T option not to create boot directory under {standby emmc}/boot.
https://tier4.atlassian.net/browse/T4PB-16833

fix: use cp -T not to create {nvme}/boot/boot directory

---

app/ota_client_stub.py
ota_proxy/config.py
ota_proxy/db.py
ota_proxy/ota_cache.py

This PR tries to resolve the bottleneck of ota-proxy performance caused by inefficient db operation implementation.
1. remove lock in OTACacheDB class, use sqlite3’s own lock mechanism instead
2. enable WAL mode and autocommit
3. serialize requests by dispatch all db requests to a dedicated threadpool
4. refactor some parts of ota-cache module
5. minor changes:
5.1 ditch the usage of `janus.queue` as it is not so necessary in our implementation
5.2 using the std queue
5.3 decrease the backoff timeout of queue.get to 1ms
with ota-image of 1.9G, containing 73543 files
before: 490+s
after: 150+s
1. number of download errors significantly lower now(less than 10 per 100,000 requests)
2. memory usage of ota-proxy also stable now(a potential memory leak is fixed)
3. (BUG) it seems that there are …

Resolve ota-proxy performance bottleneck.

---

app/ota_client.py

This PR refactor the implementation of create_regular_files.
Previous implementation has the following problem:
1. large max memory usage
2. complicated implementation and sync logic
3. multiprocessing on I/O mainly tasks
1. schedule and dispatch create_regular_file in thread-pool
2. new implementation for hardlink file handling
3. callback based stats collecting and processing
4. use `time.thread_time` to track the download time cost
5. special handling for empty file on `Downloader`(create file directly without request remote)
6. other minor updates

ota_client: create_regular_files refactor

---

app/ota_client_stub.py
ota_proxy/config.py
ota_proxy/db.py
ota_proxy/ota_cache.py
ota_proxy/server_app.py

This PR fix bugs found on the 20220513 benchmark test.
1. when space hardlimit reached, ota-update will failed
cause: when reached hardlimit, cache will be disable, failing the cache stream
solution: disable cache stream when storage reach hardlimit
2. ota-client will hang if apply ota-update when status==SUCCESS
cause: scrub_cache_event is not set under status==SUCCESS or cache_init=True but ota_client_service always wait for the event
solution: set scrub_cache_event in all needed situation
3. ota-client will fail if the ota-proxy database scheme changed
solution: database scheme version is recorded now and reflected in the database table name
1. ota_proxy.uvicorn: concurrency limit raises up to 256
2. disk usage limit raises from 60:70 to 70:80
3. ~~unknown OTA-File-Cache-Control …

Bug fix-20220513

---

app/configs.py
app/ota_client.py

Previously, we directly cap the `max_workers` of threadpool to `7` for all operations(copy, link, download).
That is not so flexible and not so compatible to different machine. This PR changes the limitation mechanism from capping `max_workers` of threadpool, to using `Semaphore` to limit the total number concurrent tasks(copy, link, download), and apply another Semaphore to specially limit the on-going downloading tasks.
1. Apply semaphore(set to 128 currently) to all operations(copy, link, download).
2. Apply semaphore(set to 16 currently) to download operation.
3. Above settings and some other settings are configured at `configs.py`.
4. Use dataclass for all Inf class.

New way to limit resource usage for ota-client during ota-update.

---

app/ota_client.py
app/ota_metadata.py
tests/test_ota_metadata.py

1. This PR introduce the support for new new RegularInf scheme that supports distinguishing hardlink group.
The new format for RegularInf is defined as follow:
```python3
format: mode,uid,gid,link number,sha256sum,'path/to/file'[,size[,inode]]
example: 0644,1000,1000,1,0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef,'path/to/file',1234,12345678
NOTE: size and inode sections are both optional, if inode exists, size must exist.
```
2. relocate Inf related classes to `ota_metadata.py`.
3. introduce tests files for Inf related classes.
4. update hardlink tracker to support hardlink group.

Support new RegularInf scheme and cleanup Inf related classes.

---

app/boot_control/cboot.py
app/boot_control/common.py
app/boot_control/grub.py
app/boot_control/interface.py
app/errors.py
app/ota_client.py

This PR introduce refinement over otastatus transition logic.
otastatus should relate to the update/rollback operation, not relate to the slots' status.
A **SUCCESS** status only means the latest update/rollback operation is successful, 
meanwhile a **FAILURE** status only means a failed update/rollback attempt.
some basic rules are enforced as follow:
1. only the most recent successfully updated slot has the **SUCCESS** status, inactive slot always in **FAILURE** status, except for the case in 2.
2. **UPDATING/ROLLBACKING** are only set to standby slot that is receiving an update/rollback.
3. otaclient will only refer to current booted slot's otastatus file when launching itself.
4. slot switch will only happen at local update/rollback.
1. implement new otastatus transition logic
2. …

Refinement on otastatus transition logic

---

app/proto/__init__.py
app/proto/wrapper.py
pyproject.toml
tests/test_proto/test_wrapper.py

The generated protobuf code is not so convenient for directly use, according to protobuf documentation, 
> **Note**
> Protocol buffer classes are basically data holders (like structs in C) that don't provide additional functionality; they don't make good first class citizens in an object model.
If we want to bind methods to customize the behaviors of the protobuf classes, the documentation recommends to implement wrappers around the generated classes.
> If you want to add richer behavior to a generated class, the best way to do this is to wrap the generated protocol buffer class in an application-specific class. 
This PR implements a proxy type of wrappers for the generated protobuf code under the `app/proto` folder.
**NOTE**: The implemented wrappers are not yet integrated into the …

Introduce wrapper for generated protobuf code

---

app/boot_control/cboot.py
app/boot_control/common.py
app/boot_control/grub.py
app/boot_control/interface.py
app/ecu_info.py
app/errors.py
app/ota_client.py
app/ota_client_call.py
app/ota_client_stub.py
app/proto/__init__.py
app/proto/wrapper.py
pyproject.toml
tests/test_proto/test_wrapper.py

This PR fixes some bugs and do some refinement over the ota_client_stub.
1. [T4PB-19284](https://tier4.atlassian.net/browse/T4PB-19284): 
- now the unreachable subecu will be labelled as `RECOVERABLE` status by mainecu when it is unreachable.
- mainecu will keep waiting for unreachable subecu when updating, it is the end user's decision to interrupt the update session(by reboot all ecus) if unreachable subecus keep losing contact. 
2. [T4PB-19316](https://tier4.atlassian.net/browse/T4PB-19316):
- status API now return the **current** running image's version instead of the updating version when receiving update.
- https://tier4.atlassian.net/browse/T4PB-19101
3. ~~[T4PB-19283](https://tier4.atlassian.net/browse/T4PB-19283):~~
~~- in previous `ecu_info.py`, the following code caused the …

Bug fix and refinement over ota_client_stub

---

app/common.py
app/errors.py
app/ota_client.py
app/ota_client_stub.py

This PR fix the issue that prevent otaclient recovering from a RECOVERABLE ota failure(like network errors). The cause of this issue is the `OTAUpdateFSM` doesn't  take otaclient failure and ota service failure into account, make otaclient/ota_service keep waiting even ota_service/otaclient failed.
1. update `OTAUpdateFSM`, implement `on_<otaclient/otaservice>_failed`methods to allow interrupting fsm on failure,
2. `OTAUpdateFSM` wait methods now support return a bool to indicate the waited event is successful or not,
3. updates `ota_client_stub` and `ota_client` according to `OTAUpdateFSM` changes,
4. define `E_OTAPROXY_FAILED_TO_START` OTAError type, ota_proxy lauching failed now will be reported by the otaclient.

Fix otaclient failed to recover from a RECOVERABLE ota failure

---

app/boot_control/cboot.py
app/boot_control/common.py
app/boot_control/grub.py
app/common.py
app/configs.py
app/main.py
tests/test_common.py

This PR fixes and updates the boot_control module modules. It fixes the behavior of parsing/processing `grub.conf` for grub controller, and minor updates to cboot controller.
1. grub: now grub controller find entry by looking up the `linux` line of the entry menu, instead of parsing the menu title(which is not recommended by the grub document). These changes fix the issue [[OTA] OTA client installed with USB installer doesn't work properly](https://tier4.atlassian.net/browse/T4PB-20054).
2. grub: `find_entry` will find and return the FIRST matching entry by kernel, assuming that the FIRST matched entry is the normal entry, not the recovery entry(in normal cases this assumption is correct).
3. common: rename <read|write>_to_file to <read|write>_str_to_file to avoid ambiguous.
4. cboot: …

[RC] Refine boot control module

---

otaclient/app/configs.py
otaclient/app/ota_metadata.py
tests/conftest.py
tests/test_ota_metadata.py

This PR makes otaclient search for `CERTS_DIR` and `VERSION` file by searching under `otaclient` package root, and move the configuration constant to `configs.py`.
This behavior is aligned to the `autoware_ecu_system_setup` ansible task file, which install certs folder and version file under `{{ ota_client_install_dir }}`(the otaclient package root).

Update certs folder discovery mechanism.

---

otaclient/app/ota_client.py

This PR fixes the otaclient's behavior that otaclient should wait on subecus with otastatus as `POST_PROCESSING`.
1. `INITIAL` and `POST_PROCESSING` otastatus are now set in the main entrance of `OTAUpdater` class(the `execute` method);
2. remove `OTAUpdater._post_update` method, directly call the `_boot_control.post_update` method as the Updater itself doesn't do anything during the post_update.

Bugfix: otaclient should wait on subecus with POST_PROCESSING status

---

otaclient/app/ota_client.py
otaclient/app/ota_client_stub.py
otaclient/app/update_stats.py
tests/test_ota_client_stub.py
tests/utils.py

This PR fix the otaclient status API doesn't report ota update progress after recovering from an recoverable OTA failure.
(NOT SURE) For the unexpected behavior that mainecu reboots before all subecus finish their update, a possible fix is applied, check changes.4 for detail. 
1. fix `OTAUpdateStatsCollector` start/stop method, make it properly restart during recovering from an failed OTA update;
2. `OTAUpdateStatsCollector` start method now always shutdown a previously active collector if any;
3. fix `test_ota_client_stub.Test_SubECUTracker`, previous test implementation provides negative success result and doesn't test the `_SubECUTracker` properly.
4. `ota_client_stub._SubECUTracker` now will wait for 30s before starting to loop pulling the subecus' status. …

Fix T4PB-20863: OTA update stats collector doesn't restart properly

---

otaclient/app/create_standby/rebuild_mode.py
otaclient/app/ota_metadata.py

This PR fix the behavior that sign.pem being downloaded twice.
* certificate is not considered as image metafile anymore, get_metafiles(get_img_metafiles) now only return directory, symboliclink, regular and persistent
* certificate is only download once for verifying metadata

Fix sign.pem being downloaded twice

---

otaclient/app/boot_control/configs.py
otaclient/app/boot_control/selecter.py
otaclient/app/ecu_info.py
otaclient/app/ota_client_stub.py
tests/test_ecu_info.py
tests/test_ota_client_stub.py

This PR follows #178 , add support for a new field `bootloader` in `ecu_info.yaml` which specifies the bootloader running with, and finishes up the support for new bootloader specification mechanism.
**NOTE: this PR is the 2nd PR of a total 3 PRs that introduces raspberry pi support for otaclient.**
1. use dataclass to refactor `ECUInfo` class, now `ecu_info.yaml` definition/parsing is using the same mechanism as `ota_metadata` definition/parsing, fields are defined programmaticly,
2. ota_client_stub now first queries `ECUInfo` to get bootloader information, if not specified, then fallback to use `detect_bootloader` function from `boot_control` module,
3. update test files, other related updates.

Add new field in ecu_info.yaml and support new bootloader specification mechanism

---

.github/workflows/test.yml
otaclient/app/configs.py
otaclient/app/ota_client_stub.py
otaclient/ota_proxy/__main__.py
otaclient/ota_proxy/config.py
otaclient/ota_proxy/db.py
otaclient/ota_proxy/ota_cache.py
otaclient/requirements.txt
tests/test_ota_proxy/test_ota_cache.py
tests/test_ota_proxy/test_ota_proxy_server.py

This PR fixes the issue caused by unwanted timeout implemented in previous PR for ota-proxy, and optimizes some implementation.
1. fix and refine `OngoingCacheTracker`, resolve the unwanted timeout issue, resolve the edge condition that subscriber subscribes on closed tracker,
2. move more configuration to `ota_proxy.config` instead of hard-coded,
3. fix and refine the `RemoteOTAFile`, simplify the background_cache_writing logic and cache commit logic,
4. refine `OTACache.retrieve_file`,
5. deps: bump uvicorn==0.20.0, aiofiles==22.1.0, and pin aiohttp==3.8.1,
6. optimize ota_proxy configuration according to test result,
7. test files updates,
8. other minor updates.
1. `MAX_DOWNLOAD_THREAD` reduces from 8 to 3, as the benefit is not significant,
2. use `uvloop` for `ota-proxy`, which …

[Bugfix/refinement] ota-proxy timeout issue

---

otaclient/ota_proxy/config.py
otaclient/ota_proxy/errors.py
otaclient/ota_proxy/ota_cache.py
otaclient/ota_proxy/server_app.py
tests/conftest.py
tests/test_ota_proxy/test_ota_cache.py
tests/test_ota_proxy/test_ota_proxy_server.py
tests/utils.py

This PR fixes a bug on cache_tracker implementation, which might fail the multiple cache streaming even the cache is successfully finished, also introduces a refactoring to otaproxy, which changes the implementation from multithreading+queue to asyncio+async_generator.
In result this PR improves the performance in all network environment, while significatntly reduce/stabilize the memory usage and CPU usage, and stabilize the overall otaproxy running. 
1. one ota-proxy instance on VM, 5 clients on host machine
2. network: tc controlled network(43ms latency, 5ms jitter, 0.01% packet loss rate, 120Mbit bandwidth)
3. disk IO for ota-proxy VM: 500M
1. 147340 files, ~10G,
2. time cost: 2274s,
3. finished without errors,
1. memory usage is much more stable, starts from using 34M mem, in the end …

[bugfix/refinement] bugfix for cache_tracker, refactor otaproxy based on asyncio+async generator 

---

.github/workflows/merged.yml
.github/workflows/release.yml
.github/workflows/test.yml

I notice that Actions result show some deprecation warnings regarding some of the actions we used.
This PR update the actions we used in workflows to their latest version. 
Also it extends the timeout for test CI to 20mins as the latest otaproxy test files might require more time to complete.
* -> actions/checkout@v3
* -> actions/setup-python@v4
* -> nosborn/github-action-markdown-cli@v3.2.0
* -> MishaKav/pytest-coverage-comment@v1.1.40

Update version of actions used by workflows.

---

otaclient/ota_proxy/db.py
otaclient/ota_proxy/ota_cache.py
otaclient/ota_proxy/utils.py
tests/test_ota_proxy/test_ota_cache.py

This PR follows #184 , in #184 ota_cache is switching to asyncio+async generator model, and this PR further improve the implementation, resolving blocking code in asyncio workflow, including sha256 hashing and cache_db accessing. Now sha256 hashing and cache_db accessing are wrapped into a proxy class which provides async interface to resolve blocking.
I have done some small scale test, and found that sha256 blocks the async workflow obviously, especailly when there are many small files. In #184 although cache writing is implemented in async, but `_hash.update()` is still being directly called, which introduces blocking in async.
I try 2 tests in different settings as follow.
NOTE: the average download speed is hard to reach the full bandwidth because we have many small files,
but it will …

[Refine] otaproxy: make ota_cache fully async, resolving blocking

---

docs/README.md
otaclient/app/proxy_info.py
tests/test_ota_proxy/test_ota_proxy_server.py
tests/test_proxy_info.py

This PR aligns the default `proxy_info` settings as v2.5.4 as follow:
1. for missing `proxy_info.yaml`, a `PRE_DEFINED_PROXY_INFO_YAML` will be used:
```
enable_local_ota_proxy: true
gateway: true
```
2. the default settings for each field also aligned v2.5.4 as follow: 
```
gateway: false
enable_local_ota_proxy: false
local_ota_proxy_listen_addr: "0.0.0.0"
local_ota_proxy_listen_port: 8082
upper_ota_proxy: "" # None, not set
```
3. Update the document related to `proxy_info.yaml`.
4. clearly distinguish the terminologies of `proxy_info.yaml missing/corrupted/invalid` and `default setting`.
1. proxy_info.py: aligns the behavior as v2.5.4
2. docs/README.md: update the documents related to proxy_info.yaml, update section about config entries, add new section for special treatment when …

proxy_info: align default proxy_info settings as v2.5.4

---

otaclient/app/ota_client_stub.py

This PR fixes cloudwatch log group for ota-proxy.
Current implementation stores ota-proxy log to the single `ota-proxy` log group even multiple ecu are targeted.
By this change, ota-proxy log is saved with each ecu's log-group.
current:
all ecus logs in the vehicle for ota-proxy are saved in the same `ota-proxy` log group.
by this change:
ota-client and ota-proxy logs are saved in the same log group.

fix: log-group for ota-proxy

---

otaclient/ota_proxy/ota_cache.py

This PR fixes otaproxy spams `cache write failed: AsyncStopIteration` logs caused by `_cache_streamer` doesn't skip empty chunk.
When HTTP chunk encoding is enabled, a empty chunk will be sent to indicate the end of chunk streaming, previously the otaproxy will not skip this empty chunk and also send it to client and the caching generator. And when multiple otaproxy chained together, multiple empty chunks will be sent to the client(one more empty chunk for passing one more otaproxy), causing the problem.
1. _cache_streamer: skip the empty chunk

[Bugfix] otaproxy: fix AsyncStopIteration errors spamming

---

otaclient/app/configs.py

In #183, the MAX_DOWNLOAD_THREAD is decreased from 8 to 3 due to otaproxy and otaclient seem to be not so stable under large amount of connections. 
At that time it seems that this change doesn't reduce too much performance. But it turns out this change does degrade the performance significantly(nearly double the time cost under the same environment). 
But since #186, the otaproxy becomes much more stable and efficient than before. And the local test(check the following comment for details) shows that MAX_DOWNLOAD_THREAD==3 doesn't max out the otaclient's efficiency, and change the MAX_DOWNLOAD_THREAD back to 7 does resume the performance as before #183, meanwhile doesn't increase CPU usage and Memory Usage footprint thanks to optimization over otaproxy and otaclient.
So this PR change …

[Refinement] increase MAX_DOWNLOAD_THREAD and DOWNLOADER_CONNPOOL_SIZE_PER_THREAD

---

otaclient/app/create_standby/legacy_mode.py
otaclient/app/create_standby/rebuild_mode.py
otaclient/app/downloader.py
tests/test_downloader.py

Previously the download time recording is done by otaclient, using `time.time_thread_ns`, but due to the downloading now is done by the `downloader` module, and the downloading is done by another thread than the thread otaclient running on, so the download time recording is incorrect.
This PR fixes this issues by recording the downloading time in the downloader.
[T4PB-25099](https://tier4.atlassian.net/browse/T4PB-25099)
[T4PB-25099]: https://tier4.atlassian.net/browse/T4PB-25099?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Fix] elapsed_download_time recording

---

otaclient/ota_proxy/ota_cache.py
otaclient/ota_proxy/server_app.py

Previously otaproxy will return 500 on any unsatisfied request except 4xx(currently 403 and 404) error. This behavior is not proper, and confusing the otaclient.
This PR fixes this behavior as follow:
1. return 500 on internal otaproxy error only.
2. return 502(BAD_GATEWAY) on any connection related error.
3. return 503(SERVICE_UNAVAILABLE) on any aiohttp client error except connection error.

[Refine] otaproxy: only return 500 in unhandled unexpected otaproxy internal error

---

otaclient/requirements.txt

Bump cryptography to 39.0.1 and pyopenssl to 23.0.0 due to security concerns, check #197 for details. 
Also remove the deps to `jwt` package as not in use and caused the deps conflicts.
NOTE: pyopenssl version bump is required for cryptography version bump.

[Security] bump cryptography to 39.0.1, pyopenssl to 23.0.0

---

otaclient/app/common.py
otaclient/app/ota_metadata.py

Perception ECU using BSP32.5 will have ubuntu 18.04.5, which have python3.8 in version 3.8.0. This version of python has a bug(https://bugs.python.org/issue39215), causing RetryTaskMap unable to work properly.
```
[2023-03-10 18:42:54,036][ERROR]-otaclient.app.common:_task_dispatcher:528,dispatcher failed! SystemError("no locals when loading 'Future'")
Traceback (most recent call last):
File "/home/autoware/ota-client/otaclient/app/common.py", line 486, in _task_dispatcher
def _done_cb(_fut: Future, /):
SystemError: no locals when loading 'Future'
```
This PR handles otaclient running on py3.8.0.
1. remove type hint in `RetryTaskMap._task_dispatcher._done_cb`, minor update.
2. ota_metadata: minor fix to backward compatible with ota image without compression.

[BugFix] fix RetryTaskMap not working on py3.8.0

---

otaclient/app/common.py
otaclient/app/create_standby/rebuild_mode.py
otaclient/app/ota_client.py
otaclient/app/ota_metadata.py
tests/test_common.py

Previous implementation has a problem, it will hold all the resources related to failed task, even that retry round is finished, due to unexpected reference cycle.
This PR re-implements the `RetryTaskMap` to resolve the following issues & requirements:
- simplify the internal design and implementation.
- better memory efficiency, not consume all input iterable at first retry round.
- resolve memory leak due to reference cycle.
- better error handling on interruption/shutdown.
- caller has more control over the executing tasks.
NOTE: this PR is based on #205 .
```python
with ThreadPoolExecutor() as pool:
_mapper = RetryTaskMap(
max_concurrent=<max_conccurent_tasks>,
executor=pool,
retry_interval_f=<Callable[[int], Any]>,
max_retry=<max_retry>, 
)
for retry_round, task_result in …
```

[Refactor] re-implement RetryTaskMap

---

otaclient/app/configs.py
otaclient/app/downloader.py
otaclient/app/ota_client.py
otaclient/app/ota_metadata.py
otaclient/app/update_stats.py
tests/test_common.py
tests/test_create_standby.py
tests/test_update_stats.py

Previously, the downloading retry strategy(implemented by **RetryTaskMap** with **keep_failing_timer**) used by otaclient breaks out when **no more succeeded files keeps longer than <timeout_setting>**, there is a potential edge condition that all downloading threads are stuck by downloading large files, resulting in unwanted pre-mature breakout.
This PR fixes this edge condition by introducing another breakout condition, **no more traffic in downloader/downloader becomes inactive longer than \<limit\>**, and change the breakout logic.
The download tasks group(outer for loop) has `last_active_timestamp`, which indicates the latest unix timestamp for latest activity(either a successful task, or traffic by downloader). 
If the download tasks group stalls(becomes inactive) longer than …

[Fix&refine] new way to collect downloader stats, resolve edge condition on downloading breakout condition

---

otaclient/app/common.py
otaclient/app/create_standby/common.py
otaclient/app/ota_client.py

Previously, in `DELTA_CALCULATING` OTA stage, the local copy is prepared after the file in active slot is verified, there is chance that the file is updated after the hash verification. This PR fixes this edge condition by verifying file during the copy. 
1. create_standby: when preparing local copy, also take size information into account if the information is available(by saved active slot's OTA image meta).
1. otaclient: fix not resetting `last_failure_traceback` when new update/rollback request is received.
1. common: add a helper method `create_tmp_fname`.
[T4PB-27531](https://tier4.atlassian.net/browse/T4PB-27531)
[T4PB-27531]: https://tier4.atlassian.net/browse/T4PB-27531?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Fix] delta calculating: verify file when copying from active slot to standby slot

---

otaclient/app/downloader.py

The downloading thread is marked as active before the connection is made, which actually make the active flag meaningless. 
This PR fixes the issue by only set the downloading thread active flag after the connection is established.

[Fix] fix downloader last_active_timestamp recording

---

otaclient/_utils/__init__.py
otaclient/_utils/logging.py
otaclient/ota_proxy/ota_cache.py
otaclient/ota_proxy/server_app.py
tests/test__utils/test_logging.py

otaproxy will log errors when any request cannot be satisfied, in normal situation it is fine, but when network is disconnected, connection error loggings will flood, which is unwanted. 
This PR introduces a log filter that can suppress exceeding loggings to prevent flooding, and we define a dedicated logger only for logging connection errors.
1. utils.logging: introduce new module, and define `BurstSuppressFilter`.
2. otaproxy.server_app: suppress connection error logging(max 6 lines per 30 seconds).
3. otaproxy.ota_cache: expose aiohttp connection errors to upper caller(server_app).
4. implement test files for utils.logging.
```
[2023-04-12 16:16:08,659][INFO]-otaclient.app.ota_client:_update_standby_slot:256,start to download needed files...total_download_files_size=20,703,405,289bytes …
```

[Refine] otaproxy: suppress flooding loggings when network disconnected

---

otaclient/app/downloader.py
otaclient/app/ota_metadata.py

Previously, metadata.jwt and certificate downloading are done by directly calling `downloader.download` method, it will only retry limited times on failure. 
This PR introduce the same strategy implemented for OTA files downloading, retry downloading until the downloader becomes inactive(like network disconnected) longer than `DOWNLOAD_GROUP_INACTIVE_TIMEOUT`.

[Fix&refine] retry inifinitely on metadata.jwt and certificate downloading error

---

otaclient/app/ecu_info.py
tests/test_ecu_info.py

This PR fixes `ECUInfo` doesn't load default config when `ecu_info.yaml` is valid yaml but not valid ecu_info. 
This is caused by assignment before assertion statement.
NOTE: this PR is splited from #212. 
1. fix not loading default config when `ecu_info.yaml` is a valid yaml file but not valid ecu_info(yaml array, empty file, etc.),
2. refactor test files, cover the cases mention above.

[Fix] ecu_info: not loading default config when ecu_info.yaml is invalid in some cases

---

otaclient/ota_proxy/__init__.py
otaclient/ota_proxy/__main__.py
tests/test_ota_proxy/test_subprocess_launch_otaproxy.py

This PR introduces exposed helper functions for external launching otaproxy, supports configuring `cache_dir` and `cache_db_file` location for standalone otaproxy CLI.
1. Previously the standalone otaproxy startup cli (\_\_main__.py) **doesn't support configure cache_dir and cache_db_file location**, make the launching and testing standalone otaproxy harder as we have to modify the `otaproxy/config.py` every-time. 
2. Previously a wrapper for launching otaproxy in subprocess is implemented `ota_client_stubs`. This wrapper does the job of constructing otaproxy components, configuring ota_cache and otaproxy uvicorn server and laucnhing it in subprocess. **This reduces `ota_client_stub` module's cohesion and introduce deep coupling with otaproxy package, which is not ideal.**
The helper …

[Refinement] refinement related to otaproxy launching

---

otaclient/app/common.py
tests/test_common.py

This PR introduces `ensure_otaproxy_start` function that can be used for probing otaproxy until it is online or exceed \<timeout>.
**NOTE**: this PR is split from #212 , and intended to be used in #212, this PR only implements the function but not yet uses.
There is an interval between subECU starts updating and mainECU's otaproxy become online, as otaproxy has to take some time to launch and become ready, especially when there are left over cache files needed to be scrubbed. 
To reduce unnecessary downloading failures and retrying when otaproxy is not yet online, this PR introduces the `ensure_otaproxy_start` function,  which allow otaclient to probe otaproxy online before it starts any downloading.
Does this PR introduce breaking change?

[Refinement] common: add ensure_otaproxy_start for probing otaproxy online

---

otaclient/app/errors.py
otaclient/app/ota_client.py
otaclient/app/ota_metadata.py
tests/test_ota_metadata.py

This PR introduces the missing validation mechanism when parsing `metadata.jwt`, explicitly define default value for optional field, or raise exception on missing must_set field in `metadata.jwt`. For case of invalid `metadata.jwt`, new OTA error type for `metadata.jwt` invalid is defined in this PR.
```
Version1 JWT payload layout(revision2):
[
{"version": 1}, # must
{"directory": "dirs.txt", "hash": <sha256_hash>}, # must
{"symboliclink": "symlinks.txt", "hash": <sha256_hash>}, # must
{"regular": "regulars.txt", "hash": <sha256_hash>}, # must
{"persistent": "persistents.txt", "hash": <sha256_hash>}, # must
{"certificate": "sign.pem", "hash": <sha256_hash>}, # must
{"rootfs_directory": "data"}, # must
{"total_regular_size": "23637537004"}, # optional, added in revision1, default is `0` …
```

[Fix & Refinement] ota_metadata: implement validation over metadata.jwt

---

otaclient/app/ota_client_service.py
tests/conftest.py
tests/test_ota_client_service.py

This PR introduces some cleanup and replaces the old, duplicated codes in `ota_client_service.py` with 2 new functions, each create otaclient server instance and launch it. 
Now otaclient grpc server's address and port configurations are obtained directly in `ota_client_service`, not via `OtaClientStub`.
This PR also adds missing test files for `ota_client_service`. 
This PR is split from #212 , as part of not directly related changes.
About otaclient grpc server configuration, basically each module should only know what they need, `ota_client_stub` should only focus on API handling, so it doesn't need to know the server configuration, neither expose method to provide such information. Instead, the `ota_client_service` module should take the responsibility of loading such configuration. …

[Refinement] cleanup ota_client_service.py, implement test file

---

.flake8
pyproject.toml

This PR updates `.flake8` and `pyproject.toml` for linting configuration. 
1. flake8: add comments for why ignores E266, E501 and E203.
2. flake8: use proper glob patterns to only match generated proto files, use `extend-exclude` instead of `exclude` to apply the extra excluded config on top of defaults, not overriding it.
3. black: remove `include` config, use default value, as black will automatically search for `otaclient` package.
4. black: use proper glob patterns to only match generated proto files in `extend-exclucede`.

[Chore] update .flake8 and pyproject.toml for linting configuration

---

otaclient/app/ota_client_call.py
otaclient/app/ota_client_stub.py
tests/test_ota_client_call.py
tests/test_ota_client_service.py
tools/test_utils/_status_call.py
tools/test_utils/_update_call.py

This PR aligns the behaviors of each calls in `otaclient_call` module. Now each call will only return when ECU responds, otherwise raise `ECUNoResponse` exception.
> **Note**
> This PR is required by #212.
Previously, status call has different behavior with update/rollback calls, which is confusing. 
Also, it is not so proper for update/rollback call to return pre-set  <FailureType: Recoverable> response for unresponsive ECUs, as this will confuse the upper caller, upper caller will not be able to tell the difference between a pre-set  <FailureType: Recoverable> response and a  <FailureType: Recoverable> returned by ECU. 
1. otaclient_call: aligns each call's behavior, define ECUNoResponse exceptin.
2. otaclient_stub: integrate new otaclient_call.
3. tools/test_utils: integrate new …

[Refinement] align and regulate each call's behavior in otaclient_call module

---

otaclient/app/create_standby/common.py

This PR introduces the change that the calculated and generated download_list by `DeltaGenerator` will be shuffled before being used to download the needed OTA files.
Considering the situation that multiple ECUs that run the same image are going to update to the same new image.
It is highly possible that otaclients on these ECUs are downloading the same files at once from time to time during the whole OTA. This will reduce the cache efficiency as almost no cache hit will occur.
Currently otaproxy already supports a feature called **simultaneously cache streaming**, which when multiple request to the same file occurs, otaproxy will only request download from remote server once, and teeing the data chunks to multiple client. 
However this feature of otaproxy doesn't resolve the issue of low …

[Refinement] create_standby: shuffle the calculated download_list

---

otaclient/_utils/__init__.py
otaclient/app/downloader.py
otaclient/app/ota_client.py
tests/test_downloader.py

With the [implementation document](https://tier4.atlassian.net/l/cp/HTKBH3Yo) ready, this PR aligns `downloader` module's behavior as document, and introduce many internal refinements for improved implementation/code readability, better error handlings, minor mechanism/workflow refinement, etc.
1. `_utils`: implement a type hinting helper method `copy_callable_typehint`, which copies one callable's paras annotation to another callable,
2. `downloader`: simplify `Downloader` active detection logic, remove unused related code,
3. `downloader`, `otaclient`: now special treatment for downloading empty file is handled in `otaclient` side(skip downloading empty file on otaclient side),
4. `downloader`: define new error type `UnhandledRequestException` for exceptions from `requests` that doesn't …

[Refinement] refine downloader and align its behavior as doc

---

otaclient/app/boot_control/_rpi_boot.py
otaclient/app/common.py

There is report that rpi_boot doesn't replace `config.txt` properly in the 1st reboot after firmware update, causing 2nd reboot still boots back to old slot. I read through the source code and found that, in `common.replace_atomic`, `os.sync` is called only after `shutil.copy`, `os.replace` is not covered by `os.sync`. 
This PR fix the `common.replace_atomic` method, while insert more `os.sync` on important file preparing like linux images moving and after firmware update to ensure the changes are write to the disk.
1. `common.replace_atomic`: now `os.sync` is called AFTER `os.replace`, ensure that replace operation is also written to the disk.
1. rpi_boot: add more loggings when important files are prepared.
[RT4-5266](https://tier4.atlassian.net/browse/RT4-5266)
[RT4-5266]: …

[Fix] rpi_boot: call os.sync on all important files replacement

---

otaclient/app/boot_control/_cboot.py

This PR lifts the conditions check for `is_switching_boot`, as long as the `ota_status` and `slot_in_use` indicates that we are in finalizing switching boot stage, we do the finalizing.
If `ota_status` and `slot_in_use` indicates a successful switching boot, but `nvbootctrl` shows the slot is not `unbootable`, only issue a warning for it. (check the following section about nvbootctl for more details).
1. pre-update: set the standby_slot as `unbootable` as we are going to apply update to it,
2. post-update: set the active boot slot to standby slot,
( ... reboot ...)
3. bootctrl_init: check `is_switching_boot` by checking `ota_status`, `slot_in_use` and if this slot is marked as `unbootable`,
4. bootctrl_init: finalizing switching_boot, set this slot as `bootable(successful)`.
Setting …

[Fix] cboot.is_switching_boot: only check ota_status and slot_in_use

---

otaclient/app/boot_control/_cboot.py
tests/test_boot_control/test_cboot.py

This PR fixes the wrong usage of `nvbootctrl -t rootfs mark-boot-successful`, `mark-boot-successful` doesn't take argument and only works for current slot(although appended argument will be ignored and the command will work). 
For debug purpose, add logging of `dump-slots-info` call at cboot finishing init and post-update.
1. cboot controller use `mark-boot-successful` incorrectly, this command doesn't take argument and can only mark the current slot as successful.
1. [RT0-28367](https://tier4.atlassian.net/browse/RT0-28367)
2. investigation report: https://tier4.atlassian.net/l/cp/VZbEuJVV
[RT0-28367]: https://tier4.atlassian.net/browse/RT0-28367?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Fix] cboot: fix wrong usage of mark-boot-successful, add dump-slots-info logging

---

otaclient/app/boot_control/_grub.py
tests/test_boot_control/default_grub

This PR fixes options parsing in `boot_control.grub.update_grub_default` method. Currently implementation expects only one `=` will occur in each line of option, which is wrong as option value might include `=`.
1. `update_grub_default` method will raise exception when grub default contains option that has `=` in option value.

[Fix] boot_control.grub: fix update_grub_default

---

otaclient/app/ota_client.py
otaclient/ota_proxy/README.md
otaclient/ota_proxy/__init__.py
otaclient/ota_proxy/__main__.py
otaclient/ota_proxy/db.py
otaclient/ota_proxy/ota_cache.py
tests/test_ota_proxy/test_cachedb.py
tests/test_ota_proxy/test_ota_cache.py

> **Note**
> This PR is split from #225 . 
This PR removes the ota_cache scrubbing feature from otaproxy subprocess init, instead it introduces the mechanism of checking over the cache db file, and improve handling the case of cache db corrupted.
Previously, if there are a lot of left-over cache files(from last failed OTA), otaproxy will take a long time to start due to it will scan and validate all cache files against database records(scrubbing) before startup. This will result in blocking other ECUs that requires this otaproxy for a long time.
The original idea is that, it might be damaged files when last OTA failed. But actually the possibility of damaged cache files is low as cache files will only be registered AFTER the caching is finished, interrupted caching will not be registered …

[Refinement] otaproxy: remove cache scrubbing, instead only checking over cache db file

---

otaclient/app/boot_control/_cboot.py
otaclient/app/boot_control/_common.py

This PR fixes boot_ctrl.cboot module's error handling in `post_update` method. With this PR, all exceptions during `post_update`(and `pre_update`, `pre_rollback`, `post_rollback`) will be captured, and `BootControlPostUpdateFailed` OTA failure exception will be raised(otaclient will report OTA failure via status API request with this OTA failure exception) from the captured exception, and also a `logging.exception` will be triggered for the captured exception.
Also, `cboot._populate_boot_folder_to_separate_bootdev` is refined to increase the error handling granularity, now _failure on mounting standby boot dev_ and _failure on boot folder copying_ will be handled and logged separately.
> **Note**
> The cause of reported failure on `_populate_boot_folder_to_separate_bootdev` is not fixed …

[Fix] boot_ctrl.cboot: post_update error handling

---

otaclient/requirements.txt

grpcio v1.53.1 fixes serveral CVEs, check
1. https://github.com/tier4/ota-client/security/dependabot/10
2. https://github.com/grpc/grpc/releases/tag/v1.53.1 
for more details.
This PR supersedes #242 , as grpcio==1.53.1 includes more bugs fix after v1.53.0.

[Deps] bumps grpcio to 1.53.1

---

otaclient/_utils/__init__.py
otaclient/app/common.py
otaclient/app/downloader.py
otaclient/app/ota_metadata.py
otaclient/ota_proxy/__init__.py
otaclient/ota_proxy/cache_control.py
otaclient/ota_proxy/ota_cache.py
otaclient/ota_proxy/server_app.py
tests/test_ota_proxy/test_cache_control_header.py

> **Note**
> This PR is the first PR in a series of PRs(#244,  #245 , #246 ) that introduce extra feature to otaproxy. Each PR is implemented based on the previous PR, so these PRs should be reviewed and merged into main branch one by one.
> **Note**
> This PR has not yet updated otaproxy to support the extended header but just maintain the forward compatibility for it. Check the #245  for otaproxy feature update.
This PR introduces extension to `ota-file-cache-control header`, implements a set of helper functions and types to use this header in coding, update related otaclient modules (`downloader.py` and `ota_metadata.py`) to support such extension(with the new implemented helper code).
Two new directives for `ota-file-cache-control` header are introduced:
1. **file_sha256**: the sha256 …

[Feature] extend ota-file-cache-control header

---

docs/README.md
docs/SERVICES.md

Update document especially availale_ecu_ids.
Also docs/SERVICES.md has been updated according to DEVELOPMENT.md
N/A (no test are needed)
Current specification for available_ecu_ids is unclear.
This PR adds more descriptions.
And adds the description who need to filtering out the update reqest.

doc: update document especially available_ecu_ids

---

tools/status_monitor/configs.py
tools/status_monitor/ecu_status_box.py
tools/status_monitor/ecu_status_tracker.py
tools/status_monitor/main_win.py
tools/status_monitor/utils.py

This PR introduces some fixes and refinements to the status monitor tools.
1. fix artifacts/remaining lines when scrolling down on the main screen,
2. fix ECU index mismatched on the main screen when some of the ECUs temporarily offline(during OTA reboot),
3. fix app crash before app receives any status update from the ECU,
4. refine the scrolling area limitation on the main screen,
5. add `update_firmware_version` line to the ECU status box.

[Chore] minor update and fix to tools.status_monitor

---

otaclient/app/boot_control/_common.py
otaclient/app/boot_control/_grub.py
otaclient/app/boot_control/_rpi_boot.py
otaclient/app/boot_control/configs.py
otaclient/app/boot_control/protocol.py
otaclient/app/configs.py
otaclient/app/ota_client.py
tests/test_boot_control/test_grub.py
tests/test_boot_control/test_ota_status_control.py
tests/test_boot_control/test_rpi_boot.py
tests/test_ota_client.py

This PR introduces several internal refinements to grub boot_control implementation as follow. With this PR, grub boot_control implementation aligns with [grub boot control design](https://tier4.atlassian.net/l/cp/7XMJ6fEN) documentation.
This PR refines the grub boot_control procedures, aligns the behavior with the design document. Comparing to the previous implementation, it handles the condition of ota-partition symlink broken and migration from non-ota-partition booted system properly during boot_control loading, please check **Behavior changes** for more details.
Also, during finalizing switch boot, previously otaclient will do the ota-partition symlink switching **before** doing `grub-update`, this potentially breaks the atomic switching boot. This PR fixes this issue.
These two …

[Refinement] boot_control.grub: improve robustness against boot load/init, split out ota_status control and slot mount logic

---

otaclient/app/boot_control/_cboot.py
otaclient/app/boot_control/_grub.py
otaclient/app/boot_control/_rpi_boot.py
otaclient/app/configs.py
otaclient/app/errors.py
otaclient/app/ota_client.py
otaclient/app/ota_client_stub.py
tests/test_ota_client.py
tests/test_ota_client_stub.py

> [!NOTE]
> This PR is based on previous PR #258.
This PR introduces refinements to otaclient's error handling, including:
1. error report now covers boot controller startup failure, boot controller startup failed will not crash the otaclient anymore, and error information is available via status API,
2. simplify and flatten the error handling structure, regulate the error handling policy regarding each otaclient components,
3. refine and redefine the OTA errors definition, refine error description,
4. refine the logging when OTA error occurs.
otaclient core(`otaclient.OTAClient`) and boot controller are launched separately, exceptions during these two components startup is handled and captured, so that the whole otaclient startup procedure can finish and grpc server can be launched.
The …

[Refinement] refine error handling, error report on status API now covers boot controller startup failure

---

.github/PULL_REQUEST_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE/tag.md

Add PR template for chore/tag PRs.

[Chore] add tag PR template

---

.github/workflows/test.yml
docker/docker-compose_tests.yml
pyproject.toml
tests/requirements.txt

> [!Important]
> This PR is required by #264 , as more fine grained control over how coverage.py is executed is needed.
This PR introduces changes to run test with coverage by directly using `coverage run -m pytest`  instead of using pytest with pytest-cov plugin. 
Also, this PR bumps action `MishaKav/pytest-coverage-comment` to 1.1.49, and exposes test result with junitxml.
Check the test coverage result comment in this PR for more details.
Actually `pytest-cov` is a wrapper plugin that calls `coverage.py` underhook. According to `coverage` [documentation](https://coverage.readthedocs.io/en/latest/):
> Many people choose to use the [pytest-cov](https://pytest-cov.readthedocs.io/) plugin, but for most purposes, it is unnecessary.
Actually we don't need to use `pytest-cov` plugin for our …

[Chore] action: use coverage.py directly in test CI

---

tools/images_packer/build-cache.sh

This PR fixes build-external bash script to handle arbitrary directory.
Current implementation can't handle arbitrary rootfs image directory.
This PR fixes this issue.

fix: image path

---

otaclient/app/create_standby/rebuild_mode.py
otaclient/app/ota_client.py
tests/test_create_standby.py
tests/test_ota_client.py

By design the persist file handling stage should be in PROCESS_POSTUPDATE phase. 
However due to when migrating from old implementation, persist file handling is still implemented as part of create_standby mechanism. In newer otaclient, the create_standby stage is counted as APPLY_UPDATE phase, resulting in mismatch with design and implementation.
In real world condition, this mismatch might cause the following behavior in APPLY_UPDATE phase:
1. all files are processed, but no progress is made and phase is still stuck at APPLY_UPDATE phase,
2. if persist file handling also copying the swapfile(this is improper, it will be handled in another PR), APPLY_UPDATE will be stuck with even longer time.
This PR fixes the issue by move persist file handling out of create_standby package, and …

fix: persists file handling should be at PROCESS_POSTUPDATE phase

---

otaclient/_utils/__init__.py
otaclient/_utils/linux.py
otaclient/app/ota_client.py

This PR implements the proper way to create swapfile, and provides a workaround fix in persist file handling to handle swapfile creating.
At the time when persist file mechanism design was proposed by the original developer, handling swapfile was not considered but is wildly used in real world to create swapfile in new slot. 
By default direct copy is used to persist file from active slot to standby slot, however for swapfile, direct copy is improper(see https://wiki.archlinux.org/title/swap for the proper way of creating a swapfile) and will cost unnecessary time if the swapfile is huge.
> [!NOTE]
> In the upcoming new OTA image spec, we will no-longer handle swapfile in persist file handling hook, but handle it at dedicated hook.
1. persist file handling(in PROCESS_POSTUPDATE phase) …

fix: properly handling swapfile during persist file handling

---

otaclient/_utils/__init__.py
otaclient/_utils/linux.py
otaclient/app/common.py
otaclient/app/ota_client.py
tests/test_persist_file_handling.py

This PR backports the new persist file handling implementation from main branch to replace the old copy-tree implementation.
See #268 for more details.

refactor: backport new persist file handling implementation to v3.6.x

---

otaclient/app/log_setting.py
tests/test_log_setting.py

This PR fixes and removes the unwanted logs upload interval, refines the implementation of logs uploading.
For the refinement side, the logging upload thread now has proper exit logic implemented. At otaclient exits, the logging uploader thread will gracefully exit now.
Current log uploading has a 30 seconds interval, results in logging at the post-update phase not being uploaded.
Now the log uploader will issue HTTP posts to the ota-logger immediately after logger receives any logs. Confirm the logs uploaded as soon as the logging issued.

fix(v3.6.x): fix and refine logs uploading

---

otaclient/app/ota_client.py

This PR fixes an issue when creating new swapfile during persist_file_handling. The new swapfile's fpath is incorrect, resulting in new swapfile not being created.

fix(v3.6.x): otaclient.persist_file_handling: fix incorrect new swapfile fpath

---

otaclient/app/boot_control/_cboot.py
otaclient/app/boot_control/_common.py
otaclient/app/boot_control/_grub.py
otaclient/app/boot_control/_rpi_boot.py
otaclient/app/boot_control/firmware.py
otaclient/app/boot_control/selecter.py
otaclient/app/common.py
otaclient/app/create_standby/__init__.py
otaclient/app/create_standby/common.py
otaclient/app/create_standby/rebuild_mode.py
otaclient/app/downloader.py
otaclient/app/ecu_info.py
otaclient/app/log_setting.py
otaclient/app/main.py
otaclient/app/ota_client.py
otaclient/app/ota_client_stub.py
otaclient/app/ota_metadata.py
otaclient/app/ota_status.py
otaclient/app/proxy_info.py
otaclient/app/update_stats.py

This PR refines the otaclient logging implementation, simplify the sub modules' logger configuration, and refine the implementation of log tee handler.

refine(v3.6.x): log_setting

---

otaclient/app/ota_client_stub.py

This PR fixes an unexpected implementation details which prevents the `available_ecu_ids` for actually behaving as expected.
This is caused by: 
1. `ota_client_stub` module merges the `available_ecu_ids` from sub ECU's status response.
2. `ecu_info` parsing logic has an implicit implementation detail for backward compatibility, which when `available_ecu_ids` is not defined in the `ecu_info.yaml`, add this ECU id into this field.
The above effectively disabling the functionality of `available_ecu_ids`, unless the corresponding ECU contacts that don't need OTA also being commented out in `ecu_info.yaml`.
With this PR, now the `available_ecu_ids` field should work as expected, and the behavior aligns with the [documentation](https://tier4.atlassian.net/l/cp/AnLPYQa5), which only …

fix(v3.7.x): fix unexpected behavior related to available_ecu_ids

---

otaclient/requirements.txt

See https://github.com/tier4/ota-client/security/dependabot/26 for more details.

build(deps): bump cryptography to >=42.0.4, <43.0.0, pyopenssl to 24.1.0 in /otaclient

---

otaclient/app/boot_control/_jetson_cboot.py

This PR fixes jetson-cboot post-update that not saving firmware version file to standby slot. This might result in firmware version control not working as expected as standby slot's firmware version file is missing after every OTA.

fix(jetson-cboot): save firmware version file to standby slot

---

otaclient/app/main.py

This PR makes otaclient print out the parsed ecu_info.yaml on starts up.

refactor(otaclient): print out ecu_info.yaml on otaclient starts up

---

otaclient/app/ota_client.py

This PR makes otaclient ignores swapfile entries(`/swapfile`, `/swap.img`) during post OTA update persist file handling.
See https://github.com/tier4/pilot-auto/pull/801 for more details.

refactor: ignore swapfile entries during post-update persist files handling

---

otaclient/app/create_standby/common.py

This PR applies the following refinement to speed up the active slot scanning during delta_calculating and preparing:
1. when using thread pool executor, for each worker thread, now pre-allocated buffer area is used throughout the work's life-cycle, data reading from source files are re-using the same buffer area, avoiding unnecessary garbage collection and memory allocation.
2. not waiting for futures saving the future objects and call wait on it, instead after all tasks are scheduled, directly call `executor.shutdown(wait=True)` to wait, this will saving lots of memory and speed up the overall progress.  
3. wait for all tasks instead of wait for each folder being scanned, reduce the idling time of the thread worker.
The test is executed by update the VM from same image to same image, …

refactor: improve the performance of active slot scanning

---

src/otaclient/app/configs.py
src/otaclient/app/main.py
src/otaclient/app/ota_client_stub.py
src/otaclient/log_setting.py
tests/test_otaclient/test_log_setting.py

This PR fixes otaclient logging upload only covers `otaclient` since project layout restruct phase2, while applies some refinements over the `log_setting` module and move this module directly under `otaclient` package.
Confirm loggings from other modules rather than `otaclient` are uploaded to the cloud side.

refactor: refine log_setting to support new src layout 

---

pyproject.toml

This PR bumps the requests version to 2.32. See https://github.com/tier4/ota-client/security/dependabot/32 for more details.

deps: bump requests to 2.32 

---

src/otaclient/app/boot_control/_common.py
src/otaclient/app/boot_control/_rpi_boot.py

Previously, the `rpi_boot` module detects the active slot's slot_id by reading its fslabel, and then use this information to determine the standby slot's id. 
This turns out to be not so robust, as if the slot_id is accidentally altered, assigned with unexpected, the `rpi_boot` module will not be able to detect the problem, and future OTA will break the system as slot_ids are unexpected.
Also, the fslabel comes with file system(not partition), if the file system somehow broken, it will also break otaclient, even if the partition layout is correct.
This PR refines the rpi_boot module to detect slot by examining the partition layout, not relying on reading the fslabel. Now we explicitly require the partition layout to be:
```
Supported partition layout:
/dev/sd<x>:
- sd<x>1: fat32, …
```

refactor: rpi_boot: detects slot by partition layout, not by checking slot fslabel

---

src/otaclient_common/retry_task_map.py
tests/test_otaclient_common/test_retry_task_map.py

This PR allows `retry_task_map.ThreadPoolExecutorWithRetry` to take `initializer` and `initargs` params, it will passthrough these params down to the `ThreadPoolExecutor.__init__` to thread worker initializing.
1. internal refinement over `retry_task_map`, now the watchdog and dispatcher don't  occupy the thread pool workers anymore, there are running by dedicated `threading.Thread`.
2. internal refinement, now fut_gen(executed by main thread) will count the finished tasks.
3. reduce cognitive complexity.
4. do not launch watchdog thread if no checks will be performed.

refactor: retry_task_map now takes initializer and initargs params

---

src/otaclient/app/configs.py
src/otaclient/app/create_standby/common.py

In #308 , the active slot scanning is improved by waiting for all tasks instead of waiting for each folder being scanned, but this brings an issue that if the files processing speed is not fast enough, the pending tasks will pile up. 
This PR implements the limitation of total ongoing files scanning entries, and define the number of thread workers.

refactor: create_standby: add semaphore during delta generating to limit pending tasks in memory

---

src/otaclient_common/typing.py
tests/test_otaclient/test_configs/test_proxy_info.py

This PR lifts the type checking on `proxy_info.yaml` file's local_ota_proxy_listen_port, string value is valid now for this field.
Underneath the change, the `NetworkPort` type now will do a force int convert for the raw value to allow port number string. 
otaclient fails to load `proxy_info.yaml` due to string value is used on `local_ota_proxy_listen_port` field.

fix: proxy_info: allow to set string value to local_ota_proxy_listen_port field

---

.github/dependabot.yml

Deps version update tracking is enabled for otaclient and github actions.
For otaclient, the strategy is "increase", which for range defined only bumps lower bound.

ci(deps): enable dependabot version updates

---

src/otaclient_common/downloader.py
tests/test_otaclient_common/test_downloader.py

This PR introduces a new watchdog function for using `DownloaderPool` with `ThreadPoolExecutorWithRetry`(#314 ). This watchdog func implements breaking out retry on reaching max idling downloading timeout, typically for breaking out OTA downloading on network disconnected. 
Note that at this PR this new watchdog func is not yet integrated into otaclient, only implementation and tests are provided.

refactor: DownloaderPool: implement watchdog func for breaking on max idling timeout

---

src/otaclient/app/create_standby/common.py
src/otaclient/app/create_standby/rebuild_mode.py
src/otaclient/app/ota_client.py
src/otaclient/app/update_stats.py
src/otaclient_common/downloader.py
tests/conftest.py
tests/test_otaclient/test_create_standby.py
tests/test_otaclient/test_update_stats.py

This PR re-implements the OTA progress stats collector implementation as it is out-of-date considering the recent changes to otaclient module. The new implementation is simpler and fits the current otaclient module.
Other changes:
1. otaclient: use DownloaderPool's watchdog func instead of OTAUpdater's one.
2. fix tests cannot exit cleanly on failure due to background OTA image server process doesn't exit.
3. OTAUpdater implements a minimum 1s interval for status query and implements the cache of status response. Query frequent than min interval will be responded with cached status response.

refactor: re-implement the OTA progress stats collector

---

src/otaclient/app/ota_client.py
src/otaclient_common/persist_file_handling.py

This PR refines the persist_file_handling module's internal implementation, reduces the code cognitive complexity, and refines the workflow of entry processing. Also now otaclient won't break out the OTA on failed entry during persist file handling.
OTA will not break on failed entry during persist file handling processing.

refactor: refine persist_file_handling internal implementation

---

pyproject.toml

Currently otaclient requires many deps packages to exactly pin to a specific version, this is not very flexible and unnecessary. 
This PR loosens the package version specifying, all the packages now pin with a range with the following strategy:
1. for most packages, set the upper bound lower than the next API version, and set the lower bound to a recent usable version(**or a recent safe version if security fix is available**), for example, `cryptography>=42.0.4,<44`, in which the recent security fixed version if `42.0.4`.
2. for some packages, set the upper bound to the next revision level, for example, `requests<2.33,>=2.32`.
3. for packages without a fixed API level(with versioning schame like 0.x.y), set the upper bound to the next revision level.
4. don't set restriction on patch …

deps: loosen the deps version specifying

---

pyproject.toml

Bumps simple-sqlite3-orm to v0.2.1.
Upstream fixes a problem related to using both RETURNING and LIMIT in DELETE stmt, see https://github.com/pga2rn/simple-sqlite3-orm/pull/19 for more details.
Bumps the version fixes otaproxy not working on ubuntu 22.04 and newer.

build(deps): bump to simple-sqlite3-orm v0.2.1

---

src/otaclient/boot_control/_jetson_cboot.py

* feature: introduce firmware package control for NVIDIA Jetson device by @Bodong-Yang in https://github.com/tier4/ota-client/pull/376
* feat: add jetson-uefi boot control support, refine jetson-cboot boot control implementation by @Bodong-Yang in https://github.com/tier4/ota-client/pull/300
* fix: proxy_info: allow to set string value to local_ota_proxy_listen_port field by @Bodong-Yang in https://github.com/tier4/ota-client/pull/326
* build(deps): bump to simple-sqlite3-orm v0.2.1 by @Bodong-Yang in https://github.com/tier4/ota-client/pull/369
* refactor: improve the performance of active slot scanning by @Bodong-Yang in https://github.com/tier4/ota-client/pull/308
* refactor: project re-struct phase1, use hatch as build tool by @Bodong-Yang in …

chore: prepare release for v3.8.0

---

src/otaclient/boot_control/_jetson_cboot.py

For BSP <= r32.5.x, jetson-cboot might fail to startup due to unified_ab detection failed. This PR fixes this issue.

fix: fix jetson-cboot for BSP <= r32.5.x

---

src/otaclient_common/retry_task_map.py
tests/test_otaclient_common/test_retry_task_map.py

This PR handles an edge condition when input task iterable yields nothing, which might result in the retry_task_map hang.

refactor(otaclient_common): retry_task_map now handles edge condition when input task iterable yields no task

---

src/otaclient/boot_control/_grub.py
src/otaclient/boot_control/_jetson_common.py
tests/data/extlinux.conf-r35.4.1-template1
tests/data/extlinux.conf-r35.4.1-updated1

Currently, the boot control implementations for grub and jetson_* assume that the rootfs indicating string(in the form of `root=...`) is either using PARTUUID or UUID to specify rootfs or this string is not presented, but not covering the case of directly using device path. This PR fixes this issue and support updating rootfs indicating string that previously was by device path.
NOTE that although we support parsing device path now, we still not support device path with space!

fix(boot_control): jetson_common, grub: support detecting and update rootfs indicating string that use device path 

---

src/otaclient/app/configs.py
src/otaclient_common/retry_task_map.py

Previously, when handling failed task, the retry_task_map first releases the semaphore, and then reschedules the failed task directly without acquire the semaphore again. This results in the concurrent tasks semaphore being escaped when there are a lot of failed tasks. 
This is especially critical when the network is totally cut off, the failed tasks are pilling up and new tasks are still being scheduled, resulting in memory leaks.
This PR fixes the above problem by fixing the task_done_cb, now when handling and re-scheduling the failed tasks, the semaphore will be kept. semaphore will only be released when the task is done successfully, or the thread-pool shutdowns.
Other refinements to the retry_task_map includes:
1. watchdog: when watchdog func failed, watchdog thread will try to drain …

fix: retry_task_map: fix mem leak when network is totally cut off

---

.github/workflows/test.yaml

Also see #401 , another workaround for PR with head updated by github action bot.

ci: test CI: also triggered on PR assigned

---

.github/tools/gen_requirements_txt.py
src/otaclient/app/main.py
src/otaclient/boot_control/_common.py
src/otaclient/boot_control/_grub.py
src/otaclient/boot_control/_jetson_cboot.py
src/otaclient/boot_control/_jetson_common.py
src/otaclient/boot_control/_jetson_uefi.py
src/otaclient/boot_control/_rpi_boot.py
src/otaclient/boot_control/selecter.py
src/otaclient_common/_io.py
src/otaclient_common/common.py
tests/test_otaclient/test_boot_control/test_ota_status_control.py
tests/test_otaclient_common/test_common.py
tests/test_otaclient_common/test_io.py
tests/utils.py

This PR introduces a new module `otaclient_common._io` for holding io related helper functions with refinement.
Especially, this modules provides the following new features/changes:
1. implement new `cal_file_digest` helper function, based on python stdlib file_digest.
2. a new `write_str_to_file_atomic` method, replacing the old `write_str_to_file`, which uses the rename syscall to atomically update target file. This function is intended for writing critical config files like boot cfg files, and it is much robust to unexpected interruption, ensured by kernel rename syscall.
3. refined `symlink_atomic` func.
4. new `copyfile_atomic` func.

refactor: create otaclient_common._io module for holding io related helper funcs

---

src/ota_metadata/legacy/parser.py
src/otaclient/boot_control/_firmware_package.py
src/otaclient/configs/_cfg_consts.py
src/otaclient/configs/_ecu_info.py
src/otaclient/create_standby/__init__.py
src/otaclient_common/typing.py
tests/test_otaclient_common/test_typing.py

Enum with str type mixin is widely used in the otaclient code base, and otaclient needs to be compatible from py3.8 to py3.12, 
However, the behavior of python's enum with type mixin has a breaking change starting from py3.11. 
Roughly speaking, starting from py3.11, a new StrEnum is introduced, and it behaves like the (str, Enum) in pre-3.11, and (str, Enum) in >= py3.11 no longer behaves like the one in pre-3.11. 
Also see https://docs.python.org/3.11/library/enum.html#enum.ReprEnum for more details about the new behavior.
This PR introduces the `otaclient_common.typing.StrEnum` for unified StrEnum behavior across different python version.
For >= py3.11, we directly use the `StrEnum` from python stdlib. For < py3.11, we implement a py3.11 compatible `StrEnum`, its behavior is exactly …

refactor: use StrEnum instead of (str, Enum), and ensure StrEnum's behavior is the same as >= 3.11 across all supported python version

---

src/otaclient/_types.py

> [!NOTE]
> This PR is split from #392 , as part of otaclient re-architecture phase1.
> [!NOTE]
> The implementation introduced in this PR is not yet in use. Will be used in the following PRs. 
This PR introduces a set of types for otaclient internal use, which are decoupled and separated from specific OTA service API version.

refactor: implement otaclient internal use types

---

src/otaclient/app/ota_client.py
src/otaclient/boot_control/_common.py
src/otaclient/utils.py
tests/test_otaclient/test_create_standby.py
tests/test_otaclient/test_ota_client.py
tests/test_otaclient/test_utils.py

This PR introduces `wait_and_log` helper method, which issues logs during waiting for flag set. otaclient now uses this method when waiting for all sub ECUs before reboot. 
Other changes:
1. otaclient will issue a warning log before actually calling reboot command.
2. otaclient will sleep 6 seconds before actually reboot the system.

refactor: implement wait_and_log helper method to log periodically during waiting for all sub ECUs before reboot

---

src/otaclient/_types.py
src/otaclient/status_monitor.py
tests/test_otaclient/test_status_monitor.py

> [!NOTE]
> This PR is split from the #392 and part of the otaclient re-architecture.
> [!NOTE]
> This PR only introduces the new status_monitor, but not yet integrate it.
This PR introduces a new implementation of otaclient internal status monitor based on message queue. 
Note that the introduced new implementation is not yet integrated into the otaclient, will be done in the following PRs.

refactor: re-implement status monitor and the status report framework

---

src/ota_metadata/legacy/__init__.py
src/otaclient/app/main.py

This PR cleans up the ota_metadata.legacy package, remove the unused dynamic package proto generated package import as it is not used.

refactor(ota_metadata.legacy): remove unused dynamic import

---

src/otaclient/boot_control/_common.py
src/otaclient/boot_control/_grub.py
src/otaclient/boot_control/_jetson_cboot.py
src/otaclient/boot_control/_jetson_uefi.py
src/otaclient/boot_control/_rpi_boot.py
src/otaclient/boot_control/_slot_mnt_helper.py
src/otaclient_common/linux.py
tests/test_otaclient/test_boot_control/test_grub.py
tests/test_otaclient/test_boot_control/test_rpi_boot.py

This PR implements the robust mount/umount for SlotMountHelper. Now otaclient will try its best to ensure the mount point is clear(no other mounts on it) before mount, and for standby slot mount, also ensure the standby slot dev is not mounted before mounting. The failure reason for the mount failure will also be logged.

refactor: split slot mount helper as a standalone module, refactor to make the mount/umount more robust

---

src/otaclient/boot_control/_grub.py
src/otaclient/boot_control/_jetson_cboot.py
src/otaclient/boot_control/_jetson_uefi.py
src/otaclient/boot_control/_rpi_boot.py
src/otaclient/boot_control/protocol.py
src/otaclient/ota_core.py
src/otaclient_common/cmdhelper.py
tests/test_otaclient/test_boot_control/test_grub.py
tests/test_otaclient/test_boot_control/test_rpi_boot.py

This PR splits the reboot from boot_control post_update/post_rollback APIs, instead create new finalizing_update/finalizing_rollback APIs for reboot operation.

refactor: boot_control: split reboot from post_update/post_rollback API.

---

proto/hatch_build.py
proto/pyproject.toml
proto/src/otaclient_pb2/v2/.gitignore
proto/src/otaclient_pb2/v2/__init__.py

This PR refines the OTA API proto package build. Now the `__init__.py` of `otaclient_pb2.v2` package is not generated anymore but becomes a static file. The `api_version` config in pyproject.toml becomes reference only.

chore(proto): refine OTA API proto build

---

pyproject.toml
requirements.txt

Bump aiohttp to >=3.10.11,<3.12, see https://www.cve.org/CVERecord?id=CVE-2024-52304 for more details.

deps: bump aiohttp to >=3.10.11,<3.12

---

pyproject.toml

This is a emergency fix due to a breaking change from pyopenssl since 24.3.0. In pyopenssl 24.3.0, some of the deprecated methods are removed, including the methods used by ota_metadata package. To workaround this issue quickly before we migrate to cryptography package, pin the pyopenssl package to 24.1.0.

fix: backport(v3.8.x): pin pyopenssl verison to 24.1.0, cryptography version to 42.0.8.

---

src/ota_metadata/legacy/parser.py
src/ota_proxy/server_app.py
src/otaclient/app/ota_client.py

By design when otaclient hits HTTPError 403, 404 or 401, otaclient should interrupt the OTA immediately as these HTTP errors indicates an invalid OTA image or invalid cookies. 
However otaclient doesn't parse requests.HTTPError properly, resulting in HTTPError not being handled. 
This PR fixes this problem and aligns with design.

fix(backport v3.8.x): fix otaclient doesn't interrupt OTA properly when OTA image is invalid(hit HTTPError 403, 404 or 401)

---

pyproject.toml
requirements.txt
src/ota_metadata/legacy/parser.py
src/ota_metadata/utils/cert_store.py
src/otaclient/ota_core.py
tests/test_ota_metadata/test_ca_store.py
tools/offline_ota_image_builder/builder.py

This PR drops the pyopenssl dependency, refactors the OTA image verification logic with cryptography instead. 
Note that we don't use the cryptography's high-level x509 verification APIs as that APIs are dedicated for TLS. Instead we directly use low-level APIs to perform certificate signature & valid period check.
This PR pins the cryptography version to >=42.0.8, <45.
Major changes:
1. ota_metadata.utils.cert_store: re-implement with cryptography.
2. ota_metadata.legacy.parser: integrate the new cert_store.
https://tier4.atlassian.net/browse/RT4-13274

refactor: drop pyopenssl dependency, use cryptography to re-implement OTA image verification logic

---

src/ota_proxy/cache_streaming.py
src/ota_proxy/config.py
src/ota_proxy/ota_cache.py

This PR fixes otaproxy's background disk space usage checker not working as expected due to checker thread exits early caused by raised exception, resulting in otaproxy LRU cache rotation not being triggered on soft disk space usage reached and otaproxy cache disabled on hard space usage reached.
This PR also backports a minor fix PR #418 .
Other changes include:
1. ota_proxy: increase soft limit to 90% disk usage, hard limit to 92% disk usage.

fix(backport v3.8.x): ota_proxy: fix disk space usage checker not working & backport #418

---

src/ota_proxy/ota_cache.py

This PR simplifies the request handling flow, instead of implementing the guard conditions checks in retrieve_file API, now the guard conditions checks are implemented within each _retrieve_file handlers.

refactor(backport v3.8.x): ota_proxy: refine request handling flow

---

src/ota_proxy/ota_cache.py

This PR simplifies the request handling flow, instead of implementing the guard conditions checks in retrieve_file API, now the guard conditions checks are implemented within each _retrieve_file handlers.
Minor fix:
1. ota_proxy: fixing the background disk space usage checker thread exits unexpectedly.
Behavior changes:
1. ota_proxy external cache feature now is enabled without checking cache_enabled flag.

refactor(ota_proxy): refine request handling flow, allow external_cache mount without cache_enabled=True, fix disk usage checker

---

src/otaclient_common/retry_task_map.py
tests/test_otaclient_common/test_retry_task_map.py

This PR introduces worker-thread-scope backoff wait on failed tasks rescheduling for otaclient_common.retry_task_map. 
For each worker thread, a `coutinues_failed_count` is maintained, when rescheduling failed tasks, now we will wait with backoff before put the failed task back into task queue.
This will help lower the CPU usage a lot when the network is fully disconnected.

feat(retry_task_map): introduce worker-thread-scope backoff wait on failed tasks rescheduling.

---

DEVELOPMENT.md

`docs/` directory is no more used, but the instructions in `DEVELOPMENT.md` still refer docs directory.
Update `DEVELOPMENT.md` to describe the current procedure.

docs: update DEVELOPMENT.md

---

pyproject.toml
requirements.txt
src/ota_proxy/__init__.py
src/ota_proxy/__main__.py
src/ota_proxy/cache_streaming.py
src/ota_proxy/ota_cache.py
src/ota_proxy/utils.py
src/otaclient/_otaproxy_ctx.py
tests/test_ota_proxy/test_cache_streaming.py
tests/test_ota_proxy/test_subprocess_launch_otaproxy.py

This PR introduces to use anyio as asyncio environment for ota_proxy, drops the use of aiofiles to use async file operations supports from anyio.
Also this PR fixes the problem of ota_proxy launched by otaclient actually not using `uvloop` although we configure to use. The main entry `run_otaproxy` is fixed and now the ota_proxy will be properly launched with uvloop.
DEPS:
1. add anyio and drop aiofiles.
2. bump to use simple-sqlite3-orm v0.7.0.

feat: ota_proxy: migrate to anyio, drop deps of aiofiles

---

src/ota_proxy/lru_cache_helper.py
src/ota_proxy/server_app.py
src/otaclient/_status_monitor.py
src/otaclient/grpc/api_v2/ecu_tracker.py
src/otaclient_common/logging.py
tests/test_otaclient_common/test_logging.py

This PR adds a helper method get_burst_suppressed_logger for creating burst_suppressed logger with ease.
Changes of integration:
1. ota_proxy: use get_burst_suppressed_logger.
2. otaclient.api_v2: use get_burst_suppressed_logger.

refactor: otaclient_common.logging: add get_burst_suppressed_logger helper for creating burst_suppressed logger

---

src/otaclient/_status_monitor.py
src/otaclient/grpc/api_v2/servicer.py
src/otaclient/ota_core.py
tests/test_otaclient/test_configs/test_ecu_info.py
tests/test_otaclient/test_configs/test_proxy_info.py

This PR implements the requirement of rejecting any OTA update/rollback request when ecu_info.yaml file is broken, and reports the failure_reason as due to ecu_info.yaml is broken.
If ecu_info.yaml is broken and cannot be parsed at startup, otaclient will set the live_ota_status to FAILURE, failure_type to UNRECOVERABLE, with failure_message: `ecu_info.yaml file is broken, please check /boot/ota/ecu_info.yaml. reject any OTA request.`
And for every incoming OTA request, otaclient will reject with failure_type.UNRECOVERABLE for every ECUs listed in the request(as otaclient with default ecu_info.yaml doesn't have contact for the sub ECUs).
For multiple ECU environment, due to when falling down to the default ecu_info, we will only have one entry(which is the main ECU) in the …

feat!: reject any OTA update/rollback request on ecu_info.yaml not properly loaded

---

src/otaclient/_status_monitor.py
src/otaclient/ota_core.py

This PR introduces an extra background thread for status_monitor, when active OTA is ongoing, it will log the otaclient status every 60seconds.

feat: status_monitor: log otaclient status every 60s when active OTA ongoing

---

docker/test_base/Dockerfile
src/otaclient/create_standby/_delta_gen.py

This PR fixes an issue which In `_delta_gen.DeltaGenFullDiskScan._process_file`, if src file is an empty file, the method will return directly without releasing the semaphore.
Tests that cover this condition has been added by adding a folder with a lot of empty files in the generated OTA image.

fix: delta_gen: fix semaphore not being reclaimed in full disk scan mode

---

src/otaclient/boot_control/_rpi_boot.py

Starting from otaclient v3.8.x, a new mechanism is used to replace the previous two-stage reboot mechanism for executing `flash-kernel`. This new mechanism will chroot into the standby slot, and call `flash-kernel` on standby slot directly to deploy new dtbs, kernel and initrd img.
However, current OTA image is configured to ignore with pattern `/tmp`, which means even the top-level `/tmp` folder will be ignored. When OTA just updates the standby slot, there will be no `/tmp` folder existed on it, causing `flash-kernel` failed due to `flash-kernel` needs `/tmp` folder during execution.
This PR fixes this problem by ensuring `/tmp` folder on standby slot.
Other changes:
1. now rpi_boot will wait for 6 seconds, and issue a logging before rebooting.

fix(v3.8.x): rpi_boot.update_firmware: ensure `/tmp` folder exists when doing flash-kernel

---

src/ota_metadata/legacy/parser.py

Related JIRA: [RT4-15059](https://tier4.atlassian.net/browse/RT4-15059)
At the beginning of OTA process, we will download "medata.jwt" file and then "certificate" pem file. 
There are cases that these files can not be downloaded correctly. 
For example:
1, ECU network config is not correct. 
2, The certificate file is not correct
etc...
When it happens, current behavior is that "otaclient" keep retry endlessly. 
For the end user, he will not be aware of the error and will likely keep waiting for a long time. 
This fix will timeout the retrying process after 5 mins. 
End user will be informed OTA is not successful after that.
[RT4-15059]: https://tier4.atlassian.net/browse/RT4-15059?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(otaclient v3.8.x): Add timeout when downloading "metadata.jwt" and *.pem files 

---

src/otaclient_common/retry_task_map.py
tests/test_otaclient_common/test_retry_task_map.py

>[!NOTE]
> This is the preceding PR for supporting OTA interruption on specific OTA metafiles cannot be downloaded due to digest mismatch caused by OTA image broken/being tempered.
This PR introduces the support of exiting on specific entry's retry count exceeding `max_retry_on_entry` for `ThreadPoolExecutorWithRetry`. Also the internal implementation of `ThreadPoolExecutorWithRetry` is refined.

feat: retry_task_map: supports exits on exceeding max_retry_on_entry  

---

src/otaclient/_otaproxy_ctx.py

By design, otaproxy life-cycle management thread should keep running at the background, start otaproxy when there is at least one ECU requires network, and shutdown otaproxy when there is no ECU requires network. 
When OTA failed and another OTA retry triggered, otaproxy ctx should start otaproxy again. However, due to otaproxy ctx thread calls **global_shutdown** when we need to close otaproxy, otaproxy ctx unexpectedly shutdown itself, and can no-longer start otaproxy anymore.
This PR fixes the above issue, only do otaproxy shutdown instead of global_shutdown when we don't need otaproxy for now, ensure that otaproxy ctx still keeps running at the background, and start/stop otaproxy in next time's OTA retry.

fix: otaproxy_ctx: fix otaproxy life-cycle management thread exits at OTA failed

---

tests/test_otaclient_common/test_retry_task_map.py

Previously, we test retry_task_map breaks out on exceeding max retry limit with doing assertion of failure_count also exceeds on main thread. 
This strategy has some problem, as retry_task_map internal breakout happens faster than retry_task_map thread pool delivers the result to the main thread, resulting in assertion failed on main thread sometime.
This PR refines the implementation of tests, now we track the failure_count by each worker thread, so that we can do accurate checking over the failure_count.

tests: refine tests for retry_task_map

---

src/otaclient/grpc/api_v2/ecu_status.py
tests/test_otaclient/test_grpc/test_api_v2/test_ecu_status.py

For ota client update, need to pass ECU status from the previous process to next process. So better to encapsulate data for process communication.
Create new  ` _ECUStatusState` class and encapsulate necessary data.
Confirmed to pass unit tests.

refactor: encapsulate data of ecu status

---

src/otaclient/grpc/api_v2/servicer.py
tests/test_otaclient/test_grpc/test_api_v2/test_servicer.py

The motivation is to add client update command. Before that, organize and remove duplicated code in servicer.
Aggregate the duplicated code for update and rollback in servicer.
Confirmed to pass the unit tests.

refactor: aggregate duplicated code in servicer

---

pyproject.toml
requirements.txt

https://tier4.atlassian.net/browse/RT4-15432
As being adviced here
https://security.snyk.io/vuln/SNYK-PYTHON-GRPCIO-9486468
Change grpcio to version listed here
https://pypi.org/project/grpcio/#history
lastest version is : 1.71.0
But it is not supported for ubuntu 18.04 and 20.04. 
So we use 1.70.0

fix: ota-client : Update grpcio version 

---

src/otaclient/boot_control/_rpi_boot.py

On raspberry pi based ECU, when OTA downgrading from otaclient v3.8.x to v3.7.1, ECU will not be able to finish up slot switching, and will boot back to previous slot.
This only happen when doing OTA downgrading.
1. OTA from otaclient v3.7.1 to v3.8.5 will work.
2. OTA from otaclient v3.8.5 to v3.8.5 will work.
This is caused by raspberry pi firmware update mechanism incompatible with old and new otaclient.
In otaclient v3.7.1, a two-stage reboot mechanism will be used to update firmware:
1. first-reboot: otaclient will do `flash-kernel` and **finalizing slot switching(critical)**, touch a flag file to indicate first-reboot finished.
2. second-reboot: basically do nothing, only clear the flag file and set OTA_STATUS to SUCCESS.
In otaclient v3.8.x, the two-stage reboot mechanism is …

fix(v3.8.x): rpi_boot: fix backward compatibility issue when OTA downgrade from otaclient v3.8.x to v3.7.1

---

pyproject.toml
requirements.txt
samples/proxy_info.yaml
src/otaclient/_logging.py
src/otaclient/configs/_proxy_info.py
tests/test_otaclient/test_configs/test_proxy_info.py
tests/test_otaclient/test_log_setting.py
tests/test_otaclient/test_logging.py

- currently, otaclient doesn't wait for logging server waking up. It cause log lost.
- otaclient support only HTTP interface for logging even though logging server supports both gRPC and HTTP.
- wait for logging server up with HTTP empty message before starting log transmission
- support both http and grpc for logging.
- otaclient try to use gRPC first. If it is not available, fallback to use HTTP. 
- In gRPC, support two types(`LOG` and `METRICS`) logging.
https://tier4.atlassian.net/wiki/spaces/OTA/pages/3481894920/OTA+Metrics
- verified the following matrix test cases
|  | otaclient v3.8.6 | otaclient with this PR |
|:---|:---:|---:|
|iot-logger v1.2.0 | (HTTP) | HTTP |
|iot-logger v1.3.0 | HTTP | gRPC |
- verified that otaclient wait for iot-logger wake up with this PR. …

feat: support both http and grpc for logging

---

.github/workflows/release_api.yml

This is the follow up PR of https://github.com/tier4/ota-client/pull/531
In new release CI, directory is not created before uploading.
NOTE: we can't trigger and can't verify the new CI behavior on Github Actions before merging the original PR into `main`. Thus this is expected as follow-up PR. But I noticed I should test by using other existing workflow...
Create directory before uploading artifact.
Verified that new Release CI passed.
https://github.com/tier4/ota-client/actions/runs/15334371280

ci: separate api release(follow-up)

---

tests/test_otaclient/test_logging.py

test_logging.py is falky([example](https://github.com/tier4/ota-client/actions/runs/15584533943/job/43887390590)).
Because pytest doesn't dispatch to logging thread in `asyncio.wait_for` function.
add `asyncio.sleep(0.1)` and wait for logging setup clearly.
Executed the target test in local for 10 times, then never meet the timeout.

test: fix flaky logging test

---

src/otaclient/client_package.py
src/otaclient_common/cmdhelper.py
tests/test_otaclient_common/test_cmdhelper.py

This issue was found in the dynamic client downloading test in Raspberry Pi.
In Raspberry Pi, for `flash-kernel`(to install dtb), some directories are binded in `Update` in chroot(dynamic client environment).
So these directories should be bind without `--make-unbindable` in initial bind(host).
remove `--make-unbindable` option from `bind_mount_rw`.
Currently, this `bind_mount_rw` function is used only from the dynamic client package preparation.
Verified that raspberry Pi update was succeeded in E2E test.
Fail to update Raspberry Pi in dynamic client.
Pass to update Raspberry Pi in dynamic client.

fix: fix mount option in bind with R/W for dynamic client

---

src/otaclient/boot_control/_grub.py
src/otaclient/boot_control/_jetson_cboot.py
src/otaclient/boot_control/_jetson_uefi.py
src/otaclient/boot_control/_rpi_boot.py
src/otaclient/boot_control/_slot_mnt_helper.py
src/otaclient/boot_control/protocol.py
src/otaclient/client_package.py
src/otaclient/main.py
tests/test_otaclient/test_client_package.py

This issue was found in the dynamic client downloading test in Raspberry Pi.
In `Update`, standby slot is requested to do 1.unmount, 2.erase then 3.mount dynamically.
In Raspberry Pi, unmount and erase(`mkfs.ext4`) is failed in chroot(dynamic client) environment because the standby slot has already been mounted in host process.
unmount the standby device before unshare in host system.
The existing tests covers new function tests.
In addition, confirmed that E2E tests are passed in VM, Roscube and Raspberry Pi.
Fail to Update in Raspberry Pi in dynamic client
Pass to Update in Raspberry Pi in dynamic client

fix: ensure standby device umounted before choort for dynamic client

---

.github/actions/generate_manifest/generate_manifest.py
.github/workflows/release.yml

The backport of https://github.com/tier4/ota-client/pull/573
squashfs filename doesn't include pre-release identification like `dev1`, `rc1`.
support to include pre-release identification into squashfs filename and version in `manifest.json`
trigger test Release CI and verified.
https://github.com/tier4/ota-client/actions/runs/15777102055
- filename
- `otaclient-x86_64-v0.1.dev1.squashfs`
-  `otaclient-arm64-v0.1.dev1.squashfs`
- manifest.json
```
{
"schema_version": "1",
"date": "2025-06-20T10:46:23.526347Z",
"packages": [
{
"filename": "otaclient-x86_64-v0.1.dev1.squashfs",
"version": "0.1.dev1",
"type": "squashfs",
"architecture": "x86_64",
"size": 71049216,
"checksum": "sha256:327fb2190a4829d888253c88f536dfe13a0d8fec33eac76b8bae14e35da2d7b4"
},
{
"filename": …
```

[backport v3.9] chore: support pre-release identification in squashfs filename

---

.github/actions/generate_manifest/generate_manifest.py
.github/workflows/release.yml

squashfs filename doesn't include pre-release identification like `dev1`, `rc1`.
support to include pre-release identification into squashfs filename and version in `manifest.json`
trigger test Release CI and verified.
https://github.com/tier4/ota-client/actions/runs/15777102055
- filename
- `otaclient-x86_64-v0.1.dev1.squashfs`
-  `otaclient-arm64-v0.1.dev1.squashfs`
- manifest.json
```
{
"schema_version": "1",
"date": "2025-06-20T10:46:23.526347Z",
"packages": [
{
"filename": "otaclient-x86_64-v0.1.dev1.squashfs",
"version": "0.1.dev1",
"type": "squashfs",
"architecture": "x86_64",
"size": 71049216,
"checksum": "sha256:327fb2190a4829d888253c88f536dfe13a0d8fec33eac76b8bae14e35da2d7b4"
},
{
"filename": "otaclient-arm64-v0.1.dev1.squashfs",
"version": "0.1.dev1",
"type": "squashfs", …
```

chore: support pre-release identification in squashfs filename

---

src/otaclient/_utils.py
src/otaclient/configs/_cfg_configurable.py
src/otaclient/configs/_cfg_consts.py
src/otaclient/main.py
src/otaclient/ota_core.py
src/otaclient_common/cmdhelper.py
tests/conftest.py

> [!NOTE]
> tmpfs is thin-provision, the size of tmpfs is the maximum allowed memory used for this mount, the actual memory usage depending on the size sum of all files currently in the tmpfs mount. 
Currently, otaclient uses `/run/otaclient` as runtime dir for holding files used during OTA(OTA image metadata, etc.).
`/run` dir is system scope shared tmpfs, typically it will have maximum size of 10% of actual memory(i.e., for a system with 8G memory, it will have 800MB tmpfs mount at `/run`).
To avoid using too much space of system scope shared `/run`, this PR introduces to use dedicated tmpfs only OTA update.
This PR implements mounting a maximum 700MB tmpfs as OTA session workdir(at `/run/otaclient/update-session`) before actually starting to handle accepted OTA request, storing OTA …

[3.9] feat: mount tmpfs as OTA update session workdir

---

src/otaclient/create_standby/delta_gen.py
src/otaclient/create_standby/resume_ota.py
src/otaclient/ota_core.py
src/otaclient_common/_io.py
tests/test_otaclient/test_create_standby/conftest.py
tests/test_otaclient/test_create_standby/test_resume_ota.py
tests/test_otaclient_common/test_io.py

When OTA with inplace update mode is interrupted when all OTA resources are collected and standby slot is cleaned up, for current implementation, next OTA retry will still try to use inplace mode. 
However, due to `.ota-tmp` is not full scan folder, and the standby slot has already being cleaned up, delta calculation will miss nearly all resources, resulting in large delta to be downloaded.
This PR introduces OTA resume when using inplace update mode.
Note that this resume doesn't mean continue the previous OTA as it, but tries with best effort to reuse the already processed delta(OTA resources) and utilize the OTA resources for current OTA.
Other changes:
1. inplace update mode with base file_table: fix issues caused by an edge case when files/dirs recorded as regular file/dir becomes …

[3.9] feat: introduce OTA resume on inplace update mode

---

src/otaclient/create_standby/utils.py
src/otaclient_common/__init__.py

This PR fixes a bug caused by `replace_root` and `TopDownCommonShortestPath` try to resolve the input paths. 
This will introduce side effect when input path is somehow not an actual dir, but a symlink, on the active slot.
The path will be resolved by looking at current rootfs filesystem, which is unexpected if the input path should be relative to standby slot during delta calculation.
Also, paths resolve is not needed in the first place, so the change here doesn't break the current behavior.

[3.9] fix: replace_root and TopDownCommonShortestPath: DO NOT resolve input paths

---

src/ota_metadata/legacy2/metadata.py
src/otaclient/client_package.py
src/otaclient/ota_core.py
tests/test_ota_metadata/test_legacy2/test_metadata.py

Currently, metadata parsing is performed during client updates.
However, this step is unnecessary, as only certificate and signature verification are required.
Removing metadata parsing could reduce the update time by approximately 20 seconds.
Skip metadata parsing for client update, just verify cert/signature verification.
parse metadata in `ClientUpdate`.
skip to parse metadata in `ClientUpdate`.

refinement: skip metafiles parsing for client update

---

src/otaclient/metrics.py
src/otaclient/ota_core.py
tests/test_otaclient/test_ota_core.py

Currently, metrics is published before exception handling. As a result, any error information is not contained in the metrics.
Publish metrics after exception handling in `Update` method.
Verified the actual behavior and failure information is stored in metrics.
```
Jul 30 15:09:03 autoware-ecu python3[120866]: [2025-07-30 15:09:03,558][INFO]-otaclient.metrics:publish:122,{"initializing_start_timestamp": 1753855717, "processing_metadata_start_timestamp": 1753855719, "delta_calculation_start_timestamp": 0, "download_start_timestamp": 0, "apply_update_start_timestamp": 0, "post_update_start_timestamp": 0, "finalizing_update_start_timestamp": 0, "ecu_id": "autoware", "session_id": "1753855717-20250717101703-test_beta-v4_3-lin-e6200e35", "current_firmware_version": "20250425-v3.0.4-release", …
```

fix: publish metrics after exceptions handling

---

src/otaclient/_logging.py
tests/test_otaclient/test_logging.py

Currently, we cannot update `/boot/ota/proxy_info.yaml` because it is not included in the OTA image.
If `proxy_info.yaml` doesn't contain gRPC endpoint, sub-ECUs can't publish the metrics to main ECU.
Use HTTP host with default gRPC port(8084) for gRPC communication as workaround, since their hosts are essentially the same.
In the future, once we can update proxy_info.yaml, we should switch to using the dedicated gRPC endpoint in proxy_info.yaml.
sub ECUs use HTTP for logging and can't publish metrics to CloudWatch
sub ECUs use gRPC for logging adn publish metrics to CloudWatch.
Does this PR introduce breaking change?

feat!: use HTTP host for gRPC endpoint

---

src/otaclient/_otaproxy_ctx.py

This PR disables the otaproxy cache on child ECU(child ECU is ECU that has `upper_ota_proxy` configured) in multiple ECUs environment, no matter how `enable_local_ota_proxy_cache` is configured.
The motivation is, starting from otaclient v3.9.1, we have OTA resume feature(requires inplace mode), so for child ECU, we don't need rely on OTA cache to speed up the OTA retry anymore.
However, due to proxy_info.yaml is forced preserved across each OTA(unfortunately this is ensured by multiple methods from multiple area), updating proxy_info.yaml via OTA is currently impossible, so this PR comes up.

refactor!: otaproxy: for multiple ECUs environment, disable OTA cache for child ECUs

---

src/ota_proxy/cache_streaming.py
src/ota_proxy/errors.py
src/ota_proxy/ota_cache.py
tests/test_ota_proxy/test_cache_streaming.py

This PR fixes an issue of OTA cache commit will fail when the cache file is already presented. Now otaproxy will check whether the cache file to save already exists or not, if that is a file, skip overriding the file.
This kind of thing happens when previous OTA is interrupted, and there is a chance the cache file is saved but the cache entry is not committed to the database.

fix: otaproxy cannot commit cache to db when the cache entry already exists

---

src/otaclient/metrics.py
src/otaclient/ota_core.py
tests/test_otaclient/test_ota_core.py

backport c1063e3273b8a9459cc639577c00de483b805c14 from https://github.com/tier4/ota-client/pull/609

[3.10] fix: publish metrics after exceptions handling (#609)

---

src/otaclient/create_standby/update_slot.py
tests/test_otaclient/test_create_standby/test_update_slot_e2e.py

backport 90c4e465389fc1adfbd5754315870f4286dc9e96 from https://github.com/tier4/ota-client/pull/612

[3.10] fix: update_slot doesn't raise exception on process_regular_files failed(#612)

---

src/ota_proxy/ota_cache.py
src/otaclient/metrics.py
tests/test_ota_proxy/test_ota_cache.py
tests/test_otaclient/test_metrics.py

backport 41a632a9f54ee10bfc9a6e05238e2a28bf5add62 from https://github.com/tier4/ota-client/pull/610

[3.10] feat: add cdn cache hit ratio into metrics (#610)

---

.github/actions/generate_manifest/generate_manifest.py
src/otaclient/errors.py
src/otaclient/ota_core.py
tests/test_otaclient/test_ota_core.py

backport d3f9255253d31aa1b3e7b502ecd6f46fab49320b from https://github.com/tier4/ota-client/pull/624

[3.10] refinement: set status as SUCCESS instead of restarting in ClientUpdate

---

src/otaclient/configs/_cfg_configurable.py
tests/test_otaclient/test_logging.py

The current log format is plain text, which is not well-suited for log management tools such as Datadog.
Migrate log format to json.
In future, would like to use DATADOG for debugging, and set retention for CloudWatch log group based on the best practice. 
Verified E2E Tests.
- Standard Output
```
(venv) root@autoware-ecu:/opt/ota/client# sudo journalctl -u otaclient -f
Aug 06 17:05:29 autoware-ecu otaclient[31283]: {"timestamp":"2025-08-06 17:05:29,186","level":"WARNING","logger":"otaclient.grpc.api_v2.ecu_status","function":"_generate_overall_status_report","line":"204","message":"new failed ECU(s) detected: {'sub', 'autoware'}, current self._state.failed_ecus_id={'sub', 'autoware'}"}
```
- [Cloud Watch](https://ap-northeast-1.console.aws.amazon.com/cloudwatch/home?region=ap-northeast-1# …

feat!: migrate to json logging

---

src/otaclient/main.py

Sometimes it takes time to wake up otaclient after rebooting
Add system uptime for logging message.
NOTE: so far, we don't add this to metrics because it is not a part of Update metrics.
example message:
```
system uptime: 0h 1m 59.0s (119.0s total)
```

chore: add system uptime debug message

---

src/otaclient/grpc/api_v2/servicer.py
src/otaclient/ota_core.py
tests/test_otaclient/test_grpc/test_api_v2/test_servicer.py

The rollback API is not used, while exposes a potential DoS vulnerability that can be utilized by attackers that has local network access to the otaclient grpc server listen address due to the request is not signed and verified.
This PR removes the actual rollback grpc API handler, replaced with a dummy handler that responds with failure `RECOVERABLE` and message `rollback support is removed`, indicating rollback API is invalid. 
TODO: redesign the rollback API to support request signing, or completely remove this API from the API definition.

fix!: remove rollback API support

---

proto/otaclient_v2.proto
src/otaclient/_types.py
src/otaclient/_utils.py
src/otaclient/grpc/api_v2/servicer.py
src/otaclient/metrics.py
src/otaclient/ota_core.py
src/otaclient_api/v2/_types.py
src/otaclient_api/v2/otaclient_v2_pb2.py
tests/test_otaclient/test_grpc/test_api_v2/test_servicer.py
tests/test_otaclient/test_ota_core.py

Currently, when OTA is requested from WebAuto, there is no common ID shared between multiple ECUs.
- session id: this ID is different between OTA execution in each ECU
Add request id as common ID shared between multiple ECUs. Then pass it to metrics to visualize the metrics against a single Request from Web Auto Agent.
- format: `<unix_timestamp_in_sec_str>-<4bytes_hex>`
- use case
- from Web Auto Agent to main ECU: `request_id` is None
- from main ECU to other ECUs: use `request_id` generated in main ECU
> [!NOTE]
> This request ID is used only for request. Not used for response so far.
Tested in multiple ECUs environment, then verified that the same request id is used between multiple ECUs.
Does this PR introduce breaking change?

feat: add request id as common ID shared between multiple ECUs

---

src/otaclient_common/cmdhelper.py

In the current OTA execution, the bottleneck is I/O.
mount standby slot with `noatime` option(= access time will not be updated when otaclient access it for hash calculartion in in-place mode)
In my opinion, we can omit the access time during OTA.
Tested on local VM.
https://tier4.atlassian.net/wiki/spaces/OTA/pages/4034625624/20250826+mount+standby+slot+with+noatime
exact same environment(snap) based on X2 beta/v4.3, same target OTA image, in-place mode, the only difference is otaclient package.
- `ota_image_total_files_size`: 38,003,183,101 bytes
- `ota_image_total_regulars_num`: 405,252
- `delta_download_files_size`: 3,943,778,246 bytes
- `delta_download_files_num`: 4,237
| Step                 | master (sec) | master w/ this change (sec) | diffs (sec) | …

refinement: mount standby slot with noatime

---

src/otaclient_common/cmdhelper.py

This PR introduces standby slot IO tuning with optimized mount options:
1. notime(already added in #654 ): do not update file accesstime.
2. commit=20: increase kernel journal commit interval to 20s, batching journal commits.
3. data=writeback,journal_async_commit: enable async journal commits, mitigate IO blocking.
By batching the journal commits into single write every `commit=N` second and enable async journal commit, the IO performance will be much better, IO stall will be mitigated, especially on slower device thanks to reduced number of disk writing calls.
See https://wiki.archlinux.org/title/Ext4, https://man.archlinux.org/man/ext4.5 for the IO optimization guide and mount options documentation.
Other changes:
1. active slot bind mount: enable `noatime` option also.
With the above …

refine: create_standby: IO tuning, optimize mount options

---

.github/workflows/release.yml

Currently, using cross platform environment(qemu) to build the squashfs for ARM. It's slow.
Migrate to use native ARM runnner.
- confirmed the squashfs build was succeeded
https://github.com/tier4/ota-client/actions/runs/17290141443
- before: 6m14s
- after: 1m24s
- confirmed the ARM based squashfs is created
```
$ unsquashfs otaclient-arm64-v0.1.dev1.squashfs
$ cd squashfs-root/
$ find . -type f -exec file {} \; | grep ELF | awk -F',' '{print $2}' | sort | uniq -c
812  ARM aarch64
```

ci: use native arm runner for squashfs release

---

src/otaclient/ota_core/_main.py
tests/test_otaclient/test_ota_core.py

This issue was found in code check.
In a dynamic client environment, if an update fails, the following issues may occur depending on task scheduling. This is because `_exit_from_dynamic_client` requests the main process to exit (restarting the otaclient service):
- session_wd may not be deleted
- metrics may not be published
execute `_exit_from_dynamic_client` after file deleting, metrics publishing and wait for 6 seconds
confirmed the behavior in E2E test.

fix: fix dynamic client exit after metrics publish 

---

pyproject.toml
tests/test_ota_proxy/test_ota_proxy_e2e.py

This PR updates and refines the otaproxy e2e test files as follow:
1. configure to output the logs from otaproxy server.
2. ota download client now is also launched from a subprocess to let each workers isolated with each other.
3. ota download client now follows otaclient's behavior, will do shuffle of the download list(shuffle 256 entries for each batch).

test: update otaproxy e2e test files

---

src/otaclient_common/retry_task_map.py
tests/test_otaclient_common/test_retry_task_map.py

This PR refines the ThreadPoolExecutorWithRetry by improving exception handling to capture and propagate the last exception raised from worker threads that triggers the interruption. The TasksEnsureFailed exception is enhanced to hold the root cause exception, providing better debugging information when tasks fail.
Caller of the ThreadPoolExecutorWithRetry now can retrieve the exception object from the TaskEnsureFailed, and use the original exception for further processing(like re-raising the original exception rather than TaskEnsureFailed).

refine: ThreadPoolExecutorWithRetry: now TaskEnsureFailed records the last exception raised from the pool on interruption
