tier4/ota-client

app/ota_client.py

すべてのファイルダウンロードで、　RAWモードのダウンロードを使用するように変更。

すべてのファイルダウンロードに_download_raw_file()を使用する

---

app/ota_client.py

traceが無いとエラーがわからないのでloggingを使ってtraceを表示させます。

use logging and logging.exception to print trace

---

app/ota_client.py
tests/conftest.py
tests/test_ota_client.py

copytree_completeのpytestを追加します。
```
sudo python3 -m pip install -r app/requirements.txt
sudo python3 -m pytest tests
```
で実行します。

[T4PB-8287] add copytree_complete test

---

app/bank.py
app/grpc_client.py
app/grub_control.py
app/ota_boot.py
app/ota_client_service.py
app/ota_metadata.py
app/ota_status.py

すでに導入済みのota_client.py以外のすべてのappソースにloggingを導入し、printのlogger置き換えを行った。

Appのすべてのソースコードにloggingを導入

---

app/grub_control.py
app/ota_client.py
tests/test_grub_control.py
tests/test_ota_client.py

kernel updateをサポートします. custom.cfg の更新をサポートします.
https://tier4.atlassian.net/browse/T4PB-7648

[T4PB-7648] support kernel update

---

app/bank.py
app/ota_boot.py
app/ota_client.py
app/ota_client_service.py
tests/test_ota_client.py

・copy_completeでコピー先のdirがない場合にエラーになる問題の修正、testの追加
・update実行時のfunction call (set_update_ecuinfo(), find_ecu_info())エラーの修正
・内部function, 外部functionのmethod名の変更
https://tier4.atlassian.net/browse/T4PB-8690
https://tier4.atlassian.net/browse/T4PB-8686
https://tier4.atlassian.net/browse/T4PB-8507

[T4PB-8690] [T4PB-8686] [T4PB-8507] copy_completeのdir問題の修正およびfunction call error対策

---

app/ota_client.py

・_gen_symbolic_links()でのchrootを行わないように変更。
・_gen_symbolic_links()でのファイル存在確認をos.path.exists()からos.path.islink()に変更

symlink作成時のchrootをやめる

---

.github/workflows/test.yml

Add a test workflow for each PR.

[T4PUB-331] Add GitHub action

---

app/ota_client.py

Also log the detail of exception when request failed.

[T4PUB-350] requests.get with timeout

---

app/grub_control.py
app/ota_boot.py
tests/grub_cfg_params.py
tests/test_grub_control.py

grub.cfgをパースすることが多いので、GrubCfgParserでmenuentryをすべて保持するように修正しました。

add entry to GrubCfgParser

---

app/grub_control.py
app/ota_boot.py
tests/grub_cfg_params.py
tests/test_grub_control.py

custom.cfgが正しく生成されない問題を修正します.
GrubCfgParserを使ってmenuentryをパースする方法に修正しています。
https://tier4.atlassian.net/browse/T4PB-9086

[T4PB-9086] fix custom cfg

---

.github/workflows/test.yml
app/requirements.txt
pyproject.toml
tests/requirements.txt

N/A
update requirements.txt for github actions

use requirements.txt

---

app/ota_client.py
tests/test_ota_client.py

_copy_complete のsrcがsymlinkの場合&&dstのsymlink-toが存在しない場合, _copy_completeが失敗する問題の修正
https://tier4.atlassian.net/browse/T4PUB-360

[T4PUB-360] Bugfix/chmod w follow symlink false

---

app/bank.py
app/ota_client_service.py
tests/test_bank.py
tests/test_grub_control.py

エラー時にraiseするようにします。
bank.py(の一部)を修正しています。(それ以外は随時修正します)
https://tier4.atlassian.net/browse/T4PUB-332

[T4PUB-332] error handling bank.py

---

app/ota_client.py

(Function of logging to file has been temporarily removed due to paralleling)

[T4PUB-349] Paralleling regular files processing

---

app/bank.py
tests/test_bank.py

bank.py用テスト項目を追加
bank.py不要コード削除

add tests for bank.py

---

app/ota_boot.py
tests/test_ota_boot.py

Added the pytest file for the ota_boot.py.
Bug Fixed: the ota_status  and return vale of OtaBoot._boot() mothod return bug.

Added the pytest file for the ota_boot.py, and fixed the ota_status bug and OtaBoot._boot() return value bug.

---

app/ota_client.py

Checking the current bank source file is symlink or not, for regular files  downloading.
https://tier4.atlassian.net/browse/T4PUB-378

[T4PUB-378] Bugfix:unintended symlink is used to copy from active bank

---

app/ota_boot.py
app/ota_status.py
tests/test_ota_boot.py
tests/test_ota_status.py

Add test code for ota_status.py.
remove try block of ota_status.py.
Generate the ota_status file, if not exist.

add  test and some refactoring for ota_status.py

---

app/ota_client.py
app/ota_metadata.py
tests/test_ota_metadata.py

・refactor ota_metadata.py
・add test code for ota_metadata.py

ota_metadata.py refactoring and add test code.

---

app/ota_boot.py
app/ota_client.py
app/ota_client_service.py
app/ota_status.py
app/otaclient_pb2.py
proto/otaclient.proto
tests/test_ota_boot.py
tests/test_ota_client_service.py

fix the boot status return bug.
add update fail status for ota_status
https://tier4.atlassian.net/browse/T4PUB-422
https://tier4.atlassian.net/browse/T4PUB-429

[T4PUB-422] [T4PUB-429] [Bugfix] boot status return and added the update fail status 

---

app/ota_client.py

・do unmount before mount
・unmount bank after update download finished.

Do unmount before mount.

---

app/ota_client.py
app/ota_client_service.py

To debug more easier, this PR adds grpc message and changes logging format like:
```
2021-08-03 17:09:13[INF][ota_client_service.py:_otaclient_service(258)] OTA Client Service start!
2021-08-03 17:09:37[INF][ota_client_service.py:EcuVersion(123)] request: 
2021-08-03 17:09:37[INF][ota_client_service.py:EcuVersion(144)] reply ecu_info {
ecu_name: "Autoware ECU"
ecu_type: "autoware"
ecu_id: "1"
version: "1.1.38"
independent: true
}
2021-08-03 17:09:37[INF][ota_client_service.py:OtaUpdate(33)] <grpc._server._Context object at 0x7f0a34a454c0>
2021-08-03 17:09:37[INF][ota_client_service.py:_ota_update(174)] my ECU ID: 1
2021-08-03 17:09:37[INF][ota_client_service.py:_ota_update(179)] execute update!!
2021-08-03 17:09:37[INF][ota_client.py:set_update_ecuinfo(1136)] _update_ecu_info start …
```

fix logging format

---

app/ota_client.py

added the symbolick link owner setting

[bugfix] add chown for symlinks.

---

app/grub_control.py

This PR appends fstab contents in the OTA image-side to the standby bank's fstab.
https://tier4.atlassian.net/browse/T4PB-10881

[T4PB-10881] fix fstab

---

README.md
app2/ota_metadata.py
docker-compose.dev.yml

- adding procedure to run test individually
- adding ota image generation to run ota on actual environment.

[T4PUB-523] test improvement

---

app/ota_metadata.py

This PR removes metadata version check. If this check exists, metadata format version can't be changed.
https://tier4.atlassian.net/browse/T4PB-12267

remove metadata version check

---

tests/requirements.txt
tests/test_ota_client-update.py

This PR adds an update test with a download error.
https://tier4.atlassian.net/browse/T4PB-11271

[T4PB-11271] add download failure test

---

app/ota_client.py
app/ota_client_service.py
app/otaclient_v2_pb2.py
proto/otaclient_v2.proto
tests/test_ota_client-status.py
tests/test_ota_client-update.py
tests/test_ota_client_service.py

This PR returns the download statistics as status.
NOTE: To use this additional status value from grpc client, app/otaclient_v2_pb2.py update is required.
https://tier4.atlassian.net/browse/T4PB-12165

[T4PB-12165] add statistics

---

app/ecu_info.py
tests/test_ecu_info.py

This PR removes ecu_info.yml format version checking, to support updating format version.
https://tier4.atlassian.net/browse/T4PB-12973

remove format version check

---

README.md
app/requirements.txt

This PR supports roscube-x setup.
Add setup in README.
https://tier4.atlassian.net/browse/T4PUB-645
OTA update on roxcue-x is confirmed.

subecu requirements txt

---

app/ota_client.py
app/ota_metadata.py
tests/test_ota_client-status.py
tests/test_ota_metadata.py

This PR supports changes: https://github.com/tier4/ota-metadata/pull/6
NOTE:
protobuf change is not yet. This will be done in another PR.
https://tier4.atlassian.net/browse/T4PB-11203
https://github.com/tier4/ota-metadata/pull/6
by modifying docker/server/Dockerfile to use https://github.com/tier4/ota-metadata/pull/6, I confirmed pytest works properly.

[T4PB-11203] add total size

---

app/extlinux_control.py

This PR fixes OTA status transition for ROSCube-X.
https://tier4.atlassian.net/browse/T4PUB-667

[T4PUB-667] fix ota status transition

---

app/otaclient_v2_pb2.py
proto/otaclient_v2.proto
tests/test_ota_client_service.py

This PR adds total_regular_file_size in protobuf.
https://tier4.atlassian.net/browse/T4PB-11203

[T4PB-11203] add total_regular_file_size

---

app/ota_client.py

This PR refers to the way of converting the unix path to URI from python's pathlib. 
The conversion and urljoin will all be done in the `Downloader` now.

ota_client: optimize the way to convert path to url

---

app/ecu_info.py
app/ota_client_stub.py
app/otaclient_v2_pb2.py
proto/otaclient_v2.proto
tests/test_ecu_info.py
tests/test_ota_client_service.py

This PR adds total_ecu_ids for status response.
This total_ecu_ids information is used for ota-client agent to detect if all ECUs are updated.
https://tier4.atlassian.net/browse/T4PB-15466

[T4PB-15466] add total_ecu_ids

---

app/ota_client_stub.py

This PR fixes illegal parameters when sub ecu is not connected on update requests.
https://tier4.atlassian.net/browse/T4PB-16828

fix: illegal param

---

app/ota_client_stub.py
app/requirements.txt
ota_proxy/config.py
ota_proxy/db.py
ota_proxy/ota_cache.py
ota_proxy/server_app.py

This PR aims to fix known and just-found bugs and improve the performance of ota-proxy.
1. LRU cache implementation is not robust
2. Other bugs found during test...
1. implement LRU cache only with db query.
2. implement simultaneously cache streaming.
3. optimize db performance by tuning db pragma settings.  
4. ota-proxy will only rotate cache if incoming entry is larger than 2KiB and smaller than 512MiB
5. other minor changes and modifications
https://tier4.atlassian.net/browse/T4PB-17245
https://tier4.atlassian.net/browse/T4PB-16832

ota-proxy enhancement 2

---

.github/workflows/test.yml
.markdownlint.yaml
.markdownlintignore
README.md
docs/README.md
emulator/README.md

This PR enables markdown lint on github actions. Currently this actions is not set as `required`, but I'd like to change as `required` after #128 is merged.
https://tier4.atlassian.net/browse/T4PB-17649

add markdown linter

---

app/errors.py
app/interface.py
app/ota_client.py
app/update_stats.py

- fix [JIRA] (T4PB-19045) [OTA] [refactor3] total_regular_file_size doesn't exist
- update the way of converting internal status class to compiled v2 proto defined structure
- ota_client.OTAUpdater: move boot_control pre_update execution to _pre_update method

Fix total_regular_file_size doesn't exist & cleanup ota_client.py

---

app/common.py

A memory leak is detected on `create_standby.common.SimpleTasksTracker`, which is caused by `SimpleTasksTracker` doesn't release retrieved `Future`. This PR fix this issue by properly storing and releasing added `Future` object.

Fix memory leak on create_slot module

---

DEVELOPMENT.md
docs/INSTALLATION.md

This PR includes a new `INSTALLATION.md` for installing/running otaclient, and update `DEVELOPMENT.md` according to changes by #156.

Update documents according to #156.

---

LICENSE.md

This PR fixes copyright owner.

fix copyright owner

---

bootstrap/root/etc/systemd/system/otaclient.service

fix: python path to use venv

---

bootstrap/root/etc/systemd/system/otaclient.service
otaclient/aws_iot_log_server/custom_http_handler.py

This PR supports systemd infinite restarting.
https://tier4.atlassian.net/browse/T4PB-24644

fix: systemd restart

---

otaclient/app/downloader.py

This PR refines the implementation of downloader decompressing and saving data chunk.
In my local setup, with compression enabled, the time cost of whole ota update reduce from *1088* down to *990*, considering my PC uses nvme and test is done with local prepared ota image, I think the performance in the real environment should also be improved in some extend.
https://tier4.atlassian.net/browse/T4PB-25078, which is handled in https://github.com/tier4/ota-client/pull/190.

[Refine] downloader: improve chunk writing and decompression

---

otaclient/app/proto/_otaclient_v2_pb2_wrapper.py

I'd like to change status v1 and v2 phase mapping:
[before chaging]
https://user-images.githubusercontent.com/58019445/228157738-8e6647e3-c018-4203-a9f4-e5c890e2c5c3.mp4
After changing phase is more natual.

fix: status phase mapping

---

.github/PULL_REQUEST_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE/feature.md
.github/PULL_REQUEST_TEMPLATE/fix.md
.github/PULL_REQUEST_TEMPLATE/refinement.md

Add templates for **feature**/**fix**/**refinement** types of PR.
1. [OTAClient development guideline](https://tier4.atlassian.net/l/cp/iKvyUuYj)

[Chore] Add PR templates

---

.github/workflows/release.yml

change release CI trigger to published release.

chore(v3.6.x): change release CI trigger to published release

---

sonar-project.properties

This PR fixes the sonarcloud setting, as the project layout is changed.

ci: fix sonarcloud setting

---

.github/workflows/test.yaml

This PR fixes the test CI according to project source code layout change.

ci: minor fix to test CI

---

pyproject.toml

See https://github.com/yaml/pyyaml/releases/tag/6.0.1 for more details.

build(deps): bump to use pyyaml 6.0.1

---

src/otaclient/app/interface.py
src/otaclient_common/downloader.py
src/otaclient_common/logging.py
src/otaclient_common/retry_task_map.py
tests/test_otaclient/test_configs/test_ecu_info.py

This minor PR fixes some typing issues. No feature or behavior changes are introduced.

chore: minor fix to typings

---

pyproject.toml
requirements.txt

See https://security.snyk.io/vuln/SNYK-PYTHON-AIOHTTP-7675597 for more details.

deps: bump aiohttp to >=3.10.2,<3.11

---

DEVELOPMENT.md

Update the test manual based on the latest code.

docs: update test manual

---

src/otaclient/boot_control/_rpi_boot.py

This is the forward port version of fix in #498, check that PR for more details.

fix: rpi_boot.update_firmware: ensure /tmp folder exists when doing flash-kernel

---

src/otaclient/grpc/api_v2/ecu_status.py
tests/test_otaclient/test_grpc/test_api_v2/test_ecu_status.py

in otaclient update, ecu status should be handover between process.
This PR introduces the serialization of ecu status by pickel.
| | pickle  | json |
| ------------- | ------------- | ------------- |
| serialize | easy  | complicated(need to serialize `StatusResponseEcuV2` by ourselves)  |
| debuggability | low | high(can read)  |
| security | low | high  |
| size | good(binary)  | not good(string)  |
| maintainability | good  | too bad  |
First, try to serialize into json. But in the implementation, realized it's not good in terms of maintainability.
Because ecu status data include multiple types(int, dict, set, object like `StatusResponseEcuV2`, event flag). We need to check each type of variable then need to serialize them in proper way. When we add new variable with new type in …

feat: add ecu status serialization by pickle

---

src/ota_metadata/legacy2/metadata.py
src/otaclient/metrics.py
src/otaclient/ota_core.py
tests/test_otaclient/test_create_standby.py
tests/test_otaclient/test_logging.py
tests/test_otaclient/test_metrics.py
tests/test_otaclient/test_ota_core.py

Currently, there is no metrics for ota-client
Implement metrics logging for `Update` API.
https://tier4.atlassian.net/wiki/spaces/OTA/pages/3481894920/OTA+Metrics
Verified that the expected metrics log was output into [CloudWatch](https://ap-northeast-1.console.aws.amazon.com/cloudwatch/home?region=ap-northeast-1#logsV2:log-groups/log-group/$252Faws$252Fgreengrass$252Fedge$252Fap-northeast-1$252F947232557913$252Ffms-prd-edge-otaclient-metrics/log-events/2025$252F05$252F14$252Ffms-prd-edge-d0c63b12-37b3-45d4-a10e-e2a149c9dbd1-Core$252Fautoware) in E2E test.
Implement metrics logging for `Update` API. The metrics logging works in ota-core process.
Does this PR introduce breaking change?
https://tier4.atlassian.net/browse/RT4-13461

feat: implement Update metrics logging

---

src/otaclient_common/downloader.py

> [!NOTE]
> This is one of the PRs that aiming to resolve the memory related issue of otaclient.
This PR refactors the `downloader` to use `posix_fadvise` syscall to indicate kernel dropping the file caches after downloading finished.
https://tier4.atlassian.net/browse/RT4-17438

refactor: downloader: use posix_fadvise syscall to indicate kernel dropping file caches after write

---

src/otaclient/metrics.py
src/otaclient/ota_core.py

add in-place / rebuild mode metrics

chore: add in place mode metrics
